INCLUDES = -I../include -I${top_srcdir}/include
LDADD = 
DEPADD = @MPILIBLOC@
smvar_do_sharedlibs = 0

EXTRA_PROGRAMS = glpid gerr
# glpid requires mpiimpl.h and hence special compile options.
glpid_SOURCES = glpid.c
grouptest_SOURCES = grouptest.c
grouptest2_SOURCES = grouptest2.c
groupcreate_SOURCES = groupcreate.c
gtranks_SOURCES = gtranks.c
gtranks_LDADD = ../util/mtest.o
groupnullincl_SOURCES = groupnullincl.c
groupnullincl_LDADD = ../util/mtest.o
gtranksperf_SOURCES = gtranksperf.c
gtranksperf_LDADD = ../util/mtest.o

../util/mtest.o:
	(cd ../util && $(MAKE) mtest.o)
