INCLUDES = -I.. -I$(srcdir)/..
argstest_SOURCES = argstest.c
argstest_LDADD = -L.. -lmpiexec -L../../../../lib -lmpich

forktest_SOURCES = forktest.c
forktest_LDADD = -L.. -lmpiexec -L../../../../lib -lmpich

servtest_SOURCES = servtest.c
servtest_LDADD = -L.. -lmpiexec -L../../../../lib -lmpich

servtest2_SOURCES = servtest2.c
servtest2_LDADD = -L.. -lmpiexec -L../../../../lib -lmpich
