INCLUDES = -I../../include -I${srcdir}/../../include
LDADD = ../util/mtest.o 
DEPADD = @MPILIBLOC@ ../util/mtest.o
smvar_do_sharedlibs = 0

arcomplex_SOURCES = arcomplex.cxx
uallredx_SOURCES = uallredx.cxx
uallreduce_SOURCES = uallreduce.cxx
ureduce_SOURCES = ureduce.cxx
uscan_SOURCES = uscan.cxx
uexscan_SOURCES = uexscan.cxx
icbcastx_SOURCES = icbcastx.cxx
icbarrierx_SOURCES = icbarrierx.cxx
icgatherx_SOURCES = icgatherx.cxx
icgathervx_SOURCES = icgathervx.cxx
icscatterx_SOURCES = icscatterx.cxx
icscattervx_SOURCES = icscattervx.cxx
icallgatherx_SOURCES = icallgatherx.cxx
icallgathervx_SOURCES = icallgathervx.cxx
icallreducex_SOURCES = icallreducex.cxx
icreducex_SOURCES = icreducex.cxx
icalltoallx_SOURCES = icalltoallx.cxx
alltoallw2x_SOURCES = alltoallw2x.cxx
reduceboolx_SOURCES = reduceboolx.cxx

../util/mtest.o:
	(cd ../util && $(MAKE) mtest.o)
