SUBDIRS = mpi mpid util basic commands .
smvar_do_sharedlibs = 0
smvarSubdir_commonmake=
smvarSubdir_do_dependencies=no
smvar_dependenciesDummy=yes
distclean-local:
	rm -f runtests

# Test both the MPI routines and the MPICH2 command scripts
testing:
	(NOXMLCLOSE=YES && export NOXMLCLOSE && cd mpi && $(MAKE) testing)
	(XMLFILE=../mpi/summary.xml && XMLCONTINUE=YES && \
	export XMLFILE && export XMLCONTINUE && \
	cd commands && $(MAKE) testing)
