INCLUDES = -I. -I../../include -I${master_top_srcdir}/src/ch3/channels/nemesis/nemesis/include -I${master_top_srcdir}/src/include \
           -I${top_builddir}/src/include
lib${MPILIBNAME}_a_SOURCES = \
  wintcp_finalize.c  wintcp_init.c  wintcp_poll.c  wintcp_send.c wintcp_utility.c socksm.c

