## vim: set ft=automake :

noinst_PROGRAMS += structf indtype createf90 sizeof kinds trf90 get_elem_d get_elem_u

structf_SOURCES    = structf.f90
indtype_SOURCES    = indtype.f90
createf90_SOURCES  = createf90.f90
sizeof_SOURCES     = sizeof.f90
kinds_SOURCES      = kinds.f90
trf90_SOURCES      = trf90.f90
get_elem_d_SOURCES = get_elem_d.f90
get_elem_u_SOURCES = get_elem_u.f90

