INCLUDES = -I../../../../../include -I${master_top_srcdir}/src/include
shmsources = \
 ch3_finalize.c \
 ch3_init.c \
 ch3_isend.c \
 ch3_isendv.c \
 ch3_istartmsg.c \
 ch3_istartmsgv.c \
 ch3_progress.c \
 shm_memory.c \
 ch3_open_port.c \
 ch3_istartrndvmsg.c \
 ch3_istartrndvtransfer.c

lib${MPILIBNAME}_a_SOURCES = ${shmsources}

EXTRA_LIBS = libmpich2-ch3-shm.a
libmpich2-ch3-shm_a_SOURCES = ${shmsources}


