##
## Copyright 2026 Argonne National Laboratory
## SPDX-License-Identifier: Apache-2.0
##

noinst_PROGRAMS += spawnargvf03 spawnmultf03
spawnargvf03_SOURCES = spawnargvf03.f90
spawnmultf03_SOURCES = spawnmultf03.f90
