##
## Copyright (C) by Argonne National Laboratory
##     See COPYRIGHT in top-level directory
##

noinst_PROGRAMS += spawnargvf03 spawnmultf03
spawnargvf03_SOURCES = spawnargvf03.f90
spawnmultf03_SOURCES = spawnmultf03.f90
