lib${MPILIBNAME}_a_SOURCES = progress_end.c progress_poke.c progress_start.c progress_test.c progress_wait.c
INCLUDES = -I../../include -I${top_srcdir}/include -I../../../../include -I${master_top_srcdir}/src/include
