INCLUDES = -I../include -I${top_srcdir}/include
LDADD = ../util/mtest.o
DEPADD = @MPILIBLOC@ ../util/mtest.o
smvar_do_sharedlibs = 0

commcreate1_SOURCES = commcreate1.c		    
dup_SOURCES         = dup.c
dupic_SOURCES       = dupic.c
ic1_SOURCES         = ic1.c
commname_SOURCES    = commname.c
ctxalloc_SOURCES    = ctxalloc.c
ctxsplit_SOURCES    = ctxsplit.c
icgroup_SOURCES     = icgroup.c
icsplit_SOURCES     = icsplit.c
iccreate_SOURCES    = iccreate.c
cmfree_SOURCES      = cmfree.c
icm_SOURCES         = icm.c
cmsplit_SOURCES     = cmsplit.c
cmsplit2_SOURCES     = cmsplit2.c
cmsplit_type_SOURCES     = cmsplit_type.c
probe-intercomm_SOURCES = probe-intercomm.c
comm_create_group_SOURCES = comm_create_group.c
comm_group_half_SOURCES = comm_group_half.c
comm_group_rand_SOURCES = comm_group_rand.c

../util/mtest.o:
	(cd ../util && $(MAKE) mtest.o )

# A special testing target to simplify running just the comm tests
testing:
	../runtests -srcdir=$(srcdir) -tests=testlist \
		   -mpiexec=@MPIEXEC@ \
		   -xmlfile=summary.xml
clean-local:
	-rm -f summary.xml
