INCLUDES = -I../include -I${srcdir}/../include
LDADD = ../util/mtest.o
DEPADD = @MPILIBLOC@ ../util/mtest.o
smvar_do_sharedlibs = 0

# isendirecv contains features that not all systems support (e.g., the
# sincos call, not available on IRIX).
EXTRA_PROGRAMS = 
attrself_SOURCES = attrself.c
exitst1_SOURCES = exitst1.c
exitst2_SOURCES = exitst2.c
exitst3_SOURCES = exitst3.c
initstat_SOURCES = initstat.c 
version_SOURCES = version.c
timeout_SOURCES = timeout.c
finalized_SOURCES = finalized.c

../util/mtest.o:
	(cd ../util && $(MAKE) mtest.o)

# A special testing target to simplify running just the init tests
testing:
	../runtests -srcdir=$(srcdir) -tests=testlist \
		   -mpiexec=@MPIEXEC@ \
		   -xmlfile=summary.xml
clean-local:
	-rm -f summary.xml
