# -*- Mode: Makefile; -*-
#
# (C) 2008 by Argonne National Laboratory.
#     See COPYRIGHT in top-level directory.
#

SUBDIRS_HYDRA_PM = central
SUBDIRS = utils @HYDRA_PM@ .

mpich2-build-install mpich2-build-uninstall install install-alt:
	cd @HYDRA_PM@ && ${MAKE} $@
