# -*- Mode: Makefile; -*-
#
# (C) 2008 by Argonne National Laboratory.
#     See COPYRIGHT in top-level directory.
#

SUBDIRS_hydra_pm = central
SUBDIRS = utils @hydra_pm@ .

mpich2-build-install mpich2-build-uninstall install install-alt:
	cd @hydra_pm@ && ${MAKE} $@
