mpi_sources = wtime.c wtick.c
lib${MPILIBNAME}_a_SOURCES = ${mpi_sources} mpidtime.c
INCLUDES = -I../../include -I${master_top_srcdir}/src/include

profilelib_${MPILIBNAME} = ${PMPILIBNAME}
profilelib_${MPILIBNAME}_SOURCES = ${mpi_sources}
#
doc_HTML_SOURCES = ${mpi_sources}
doc_MAN_SOURCES = ${mpi_sources}
doc_LATEX_SOURCES = ${mpi_sources}
