INCLUDES = -I../include -I${srcdir}/../include
LDADD = ../util/mtest.o 
DEPADD = @MPILIBLOC@
smvar_do_sharedlibs = 0

infodup_SOURCES    = infodup.c
infodel_SOURCES    = infodel.c
infovallen_SOURCES = infovallen.c
infoorder_SOURCES  = infoorder.c
infomany_SOURCES   = infomany.c
infomany2_SOURCES  = infomany2.c
infotest_SOURCES   = infotest.c

# A special testing target to simplify running just the info tests
testing:
	../runtests -srcdir=$(srcdir) -tests=testlist \
		   -mpiexec=@MPIEXEC@ \
		   -xmlfile=summary.xml

../util/mtest.o:
	(cd ../util && $(MAKE) mtest.o)
