INCLUDES = -I../../include -I${srcdir}/../../include
LDADD = ../util/mtest.o 
DEPADD = @MPILIBLOC@ ../util/mtest.o
smvar_do_sharedlibs = 0

infodupx_SOURCES = infodupx.cxx
infodelx_SOURCES = infodelx.cxx
infovallenx_SOURCES = infovallenx.cxx
infoorderx_SOURCES = infoorderx.cxx

