INCLUDES = -I../include -I${srcdir}/../include
LDADD = ../util/mtest.o 
DEPADD = @MPILIBLOC@ ../util/mtest.o
smvar_do_sharedlibs = 0

EXTRA_PROGRAMS = 
rdwrord_SOURCES = rdwrord.c
rdwrzero_SOURCES = rdwrzero.c
getextent_SOURCES = getextent.c
setinfo_SOURCES = setinfo.c
setviewcur_SOURCES = setviewcur.c
i_noncontig_SOURCES = i_noncontig.c
async_SOURCES = async.c
async_any_SOURCES = async_any.c
userioerr_SOURCES = userioerr.c
resized_SOURCES = resized.c

../util/mtest.o:
	(cd ../util && $(MAKE) mtest.o)

# Add the temporary files that might be left behind by the test programs
clean-local:
	-@rm -f testfile testfile.?

# A special testing target to simplify running just the io tests
testing:
	../runtests -srcdir=$(srcdir) -tests=testlist \
		   -mpiexec=@MPIEXEC@ \
		   -xmlfile=summary.xml
