# -*- Mode: Makefile; -*-
#
# (C) 2008 by Argonne National Laboratory.
#     See COPYRIGHT in top-level directory.
#

SUBDIRS_hydra_ui = mpiexec
SUBDIRS = utils @hydra_ui@ .

mpich2-build-install mpich2-build-uninstall install install-alt:
	cd @hydra_ui@ && ${MAKE} $@
