LDADD = ../util/mtestf.o 
DEPADD = @MPILIBLOC@ ../util/mtestf.o
smvar_do_sharedlibs = 0

cartcrf_SOURCES = cartcrf.f
dgraph_wgtf_SOURCES = dgraph_wgtf.f
dgraph_unwgtf_SOURCES = dgraph_unwgtf.f

testing:
	../../runtests -srcdir=$(srcdir) -tests=testlist \
			-mpiexec=$(bindir)/mpiexec \
		   	-xmlfile=summary.xml

../util/mtestf.o: 
	(cd ../util && $(MAKE) mtestf.o)
