LDADD = ../util/mtestf.o 
DEPADD = @MPILIBLOC@ ../util/mtestf.o
smvar_do_sharedlibs = 0

infotestf_SOURCES = infotestf.f
infotest2f_SOURCES = infotest2f.f

../util/mtestf.o: 
	(cd ../util && $(MAKE) mtestf.o)
