#! /bin/sh
echo "RUNNING SETUP_CHANNEL FOR THE DLL CHANNEL"

#
# NOTE: This file is sourced from the setup_device with the current working
# directory set to the top-level build directory.
#

#
# Variables of interest...
#
# $with_device - device name and arguments
# $device_name - name of the device
# $device_args - contains name of channel select plus an channel args
# $channel_name - name of the channel
# $master_top_srcdir - top-level source directory
# $master_top_builddir - top-level build directory
# $ac_configure_args - all arguments passed to configure
#

pathlist=""
pathlist="$pathlist src/mpid/${device_name}/channels/${channel_name}/include"
for path in $pathlist ; do
    CPPFLAGS="$CPPFLAGS -I${master_top_builddir}/${path} -I${master_top_srcdir}/${path}"
done
#
# Add the dllchan to the other install dirs.  In turn, the dllchannel
# will make sure that the generated DLLs for the selected channels 
# are installed
other_install_dirs="$other_install_dirs src/mpid/ch3/channels/dllchan"
