# -*- Mode: Makefile; -*-
#
# (C) 2008 by Argonne National Laboratory.
#     See COPYRIGHT in top-level directory.
#

SUBDIRS = utils control pm bootstrap demux launcher .

all-preamble:
	@if [ ! -d lib ] ; then mkdir lib ; fi

mpich2-build-install mpich2-build-uninstall install install-alt:
	cd launcher && ${MAKE} $@
