#! /bin/sh
# Check that we are using the simple PMI implementation
# (Selecting multiple PM's may require incompatible PMI implementations 
# (e.g., gforker and SMPD).


if test -z "$PM_REQUIRES_PMI" ; then
    if test "$with_pmi" = "pmi2/simple" -o "$with_pmi" = "simple" ; then
        PM_REQUIRES_PMI=$with_pmi
    else
	PM_REQUIRES_PMI=simple
    fi
elif test "$PM_REQUIRES_PMI" != "simple" -a "$PM_REQUIRES_PMI" != "pmi2/simple" -a "$PM_REQUIRES_PMI" != "pmi2/poe"; then
    echo "hydra requires the \"simple\" or \"pmi2\" PMI implementation; \"$PM_REQUIRES_PMI\" has already been selected"
    exit 1
fi

