INCLUDES = -I../include -I${srcdir}/../include
LDADD = ../util/mtest.o 
DEPADD = @MPILIBLOC@ ../util/mtest.o
smvar_do_sharedlibs = 0

namepub_SOURCES = namepub.c
spawn1_SOURCES = spawn1.c
spawninfo1_SOURCES = spawninfo1.c
spawnminfo1_SOURCES = spawnminfo1.c
spawn2_SOURCES = spawn2.c
spawnintra_SOURCES = spawnintra.c
spawnargv_SOURCES = spawnargv.c
spawnmanyarg_SOURCES = spawnmanyarg.c
spaconacc_SOURCES = spaconacc.c
spaconacc2_SOURCES = spaconacc2.c
selfconacc_SOURCES = selfconacc.c
spawnmult2_SOURCES = spawnmult2.c
taskmaster_SOURCES = taskmaster.c
join_SOURCES = join.c
disconnect_reconnect_SOURCES = disconnect_reconnect.c
disconnect_reconnect2_SOURCES = disconnect_reconnect2.c
disconnect_reconnect3_SOURCES = disconnect_reconnect3.c
multiple_ports_SOURCES = multiple_ports.c
multiple_ports2_SOURCES = multiple_ports2.c
spaiccreate_SOURCES = spaiccreate.c
spaiccreate2_SOURCES = spaiccreate2.c
disconnect_SOURCES = disconnect.c
disconnect2_SOURCES = disconnect2.c
disconnect3_SOURCES = disconnect3.c
concurrent_spawns_SOURCES = concurrent_spawns.c
pgroup_connect_test_SOURCES = pgroup_connect_test.c
pgroup_intercomm_test_SOURCES = pgroup_intercomm_test.c


../util/mtest.o:
	(cd ../util && $(MAKE) mtest.o)

testing:
	../runtests -srcdir=$(srcdir) -tests=testlist \
			-mpiexec=@MPIEXEC@ \
		   	-xmlfile=summary.xml
clean-local:
	-rm -f summary.xml
