#! /bin/sh
#
# Get usage.  This runs configure --help and 
# discards the top boilerplate and lists just the features added by these
# packages.  Use
#    find . -name configure -exec `pwd`/maint/getusage \{\} \;
# to generate a list for all configures in mpich
# Removes the most common options (enable-echo, cache, and strict)
dir=$1
if [ -z "$dir" ] ; then dir=. ; fi
dir=`dirname $dir`
echo " "
echo "Configure options for $dir:"
cd $dir && ./configure --help | sed -e '1,/options recognized/d' | \
    sed -e '/enable-cache/d' -e '/enable-echo/d' -e '/enable-strict/d'
