#! /bin/sh
# Inform the top-level configure that MPD supports a nameserver
MPID_PM_NAMESERVER=mpd
# Check that we are using the simple PMI implementation
# (Selecting multiple PM's may require incompatible PMI implementations 
# (e.g., MPD and SMPD).
if [ -z "$PM_REQUIRES_PMI" ] ; then
    PM_REQUIRES_PMI=simple
elif [ "$PM_REQUIRES_PMI" != "simple" ] ; then
    echo "MPD requires the simple PMI implementation; $PM_REQUIRES_PMI has already been selected"
    exit 1
fi
