INCLUDES = -I../../include -I${srcdir}/../../include
LDADD = ../../util/mtest.o ../util/mtestthread.o
DEPADD = @MPILIBLOC@ ../../util/mtest.o ../util/mtestthread.o
smvar_do_sharedlibs = 0

# Use extra programs to list programs that should not be built by default.
EXTRA_PROGRAMS       = 

multispawn_SOURCES  = multispawn.c
th_taskmaster_SOURCES  = th_taskmaster.c

../../util/mtest.o:
	(cd ../../util && $(MAKE) mtest.o)

# A special testing target to simplify running just the thread spawn tests
testing:
	../../runtests -srcdir=$(srcdir) -tests=testlist \
		   -mpiexec=$(bindir)/mpiexec \
		   -xmlfile=summary.xml
