stdiotest_SOURCES = stdiotest.c
stdintest_SOURCES = stdintest.c
stdintest2_SOURCES = stdintest2.c
checkenv1_SOURCES = checkenv1.c
rtest_SOURCES     = rtest.c
rtestf_SOURCES    = rtestf.f
rtestx_SOURCES    = rtestx.cxx
testout_SOURCES   = testout.c

C_LINK = $(bindir)/mpicc
MPICC = $(bindir)/mpicc
MPICXX = $(bindir)/mpicxx
MPIF77 = $(bindir)/mpif77

.c:
	$(MPICC) -o $* $<
.c.o:
	$(MPICC) -c $<
.f.o:
	$(MPIF77) -c $<
.F.o:
	$(MPIF77) -c $<
.cxx.o:
	$(MPICXX) -c $<

testing:
#	./cmdtests

clean-local:
	-rm -f err.txt out.log out.txt stdintest stdintest2 sdtiotest a.out
