#! /bin/sh
# Check that we are using the simple PMI implementation
# (Selecting multiple PM's may require incompatible PMI implementations 
# (e.g., gforker and SMPD).
if [ -z "$PM_REQUIRES_PMI" ] ; then
    PM_REQUIRES_PMI=simple
elif [ "$PM_REQUIRES_PMI" != "simple" ] ; then
    echo "gforker requires the simple PMI implementation; $PM_REQUIRES_PMI has already been selected"
    exit 1
fi
