F77INCLUDES = -I. 
LDADD = ../util/mtestf.o 
DEPADD = @MPILIBLOC@ ../util/mtestf.o
spawnargvf_LDADD = @F77_GETARG_LIBS@
spawnmultf_LDADD = @F77_GETARG_LIBS@
smvar_do_sharedlibs = 0

namepubf_SOURCES = namepubf.f
spawnf_SOURCES = spawnf.f
spawnargvf_SOURCES = spawnargvf.f
spawnmultf_SOURCES = spawnmultf.f
spawnmult2f_SOURCES = spawnmult2f.f
connaccf_SOURCES = connaccf.f

testing:
	../../runtests -srcdir=$(srcdir) -tests=testlist \
			-mpiexec=$(bindir)/mpiexec \
		   	-xmlfile=summary.xml

../util/mtestf.o: 
	(cd ../util && $(MAKE) mtestf.o)
