# We don't use a general LDADD for mtestf.o because c2fmult is a C-only
# program
# "F77INCLUDES = -I." is needed when allocmemf.f is compiled,
# i.e. when cray-pointer is available, because it includes add1size.h
F77INCLUDES = -I.
INCLUDES = -I../../include -I${srcdir}/../../include
DEPADD = @MPILIBLOC@ ../util/mtestf.o ../../util/mtest.o
smvar_do_sharedlibs = 0

# allocmemf is an "extra" program because it requires a Fortran extension
EXTRA_PROGRAMS = allocmemf

allocmemf_SOURCES = allocmemf.f
allocmemf_LDADD = ../util/mtestf.o
c2f2cf_SOURCES = c2f2c.c c2f2cf.f
c2f2cf_LDADD = ../util/mtestf.o 
c2f2c_CFLAGSADD = -I../../include
ctypesinf_SOURCES = ctypesinf.f ctypesfromc.c
ctypesinf_LDADD = ../util/mtestf.o
c2fmult_SOURCES = c2fmult.c
c2fmult_LDADD = ../../util/mtest.o

# need to add this to get it to appear in ../../f90/ext/Makefile.sm
c2f90mult_LDADD = ../../util/mtest.o

testing:
	../../runtests -srcdir=$(srcdir) -tests=testlist \
			-mpiexec=$(bindir)/mpiexec \
		   	-xmlfile=summary.xml

../util/mtestf.o: 
	(cd ../util && $(MAKE) mtestf.o)

../../util/mtest.o:
	(cd ../../util && $(MAKE))
