smvar_do_sharedlibs = 0
INCLUDES = -I../../include -I${srcdir}/../../include
LDADD = ../util/mtest.o 
DEPADD = @MPILIBLOC@ ../util/mtest.o

baseenv_SOURCES = baseenv.cxx
initstatx_SOURCES = initstatx.cxx
initstat2x_SOURCES = initstat2x.cxx

../util/mtest.o: 
	(cd ../util && $(MAKE) mtest.o)
