INCLUDES = -I. -I../../include -I${master_top_srcdir}/src/ch3/channels/nemesis/nemesis/include -I${master_top_srcdir}/src/include \
           -I${top_builddir}/src/include
lib${MPILIBNAME}_a_SOURCES = \
  newtcp_module_finalize.c  newtcp_module_init.c  newtcp_module_poll.c  newtcp_module_send.c newtcp_module_utility.c socksm.c

