INCLUDES = -I../../../../include -I${master_top_srcdir}/src/include
sshmsources = \
 ch3u_get_business_card_sshm.c \
 ch3u_init_sshm.c              \
 ch3u_finalize_sshm.c          \
 ch3i_bootstrapq.c             \
 ch3i_shm_bootstrapq.c         \
 ch3u_connect_sshm.c           

lib${MPILIBNAME}_a_SOURCES =   ${sshmsources}

# Create a local library as an option
EXTRA_LIBS = libmpich-sshmutil.a
libmpich-sshmutil_a_SOURCES = ${sshmsources}

