INCLUDES = -I../../../../include -I${master_top_srcdir}/src/include
lib${MPILIBNAME}_a_SOURCES =   ch3_shm.c

# Create a local library as an option
EXTRA_LIBS = libmpich-shmutil.a
libmpich-shmutil_a_SOURCES = ch3_shm.c
