SUBDIRS = ch3

MPILIBNAME = @MPILIBNAME@
# This is temporary
# Don't build atomic by default
EXTRA_PROGRAMS = atomic atomic_fai

# Atomic tests (correctness and performance) some atomic operations.  This
# is a temporary test.
atomic_SOURCES = atomic.c
atomic_LDADD = -L../../lib -l$(MPILIBNAME)
atomic_fai_SOURCES = atomic_fai.c
atomic_fai_LDADD = -L../../lib -l$(MPILIBNAME)
INCLUDES = -I../../src/include -I${top_srcdir}/src/include 

#
# Temp tests for dll support

dluse: $(srcdir)/dluse.c libconftest.@SHLIB_EXT@
	$(CC) -o dluse -DSHLIB_EXT=@SHLIB_EXT@ $(srcdir)/dluse.c -ldl
#	$(CC) -o dluse -Wl,-export-dynamic $(srcdir)/dluse.c -ldl
dltest.lo: $(srcdir)/dltest.c
	$(C_COMPILE_SHL) -c $(srcdir)/dltest.c -o dltest.lo
libconftest.la: dltest.lo
	$(AR) cr libconftest.la dltest.lo
libconftest.@SHLIB_EXT@: libconftest.la
	../../src/util/createshlib --mode=link -version-info "1:1" \
				   -o libconftest.la -rpath `pwd`
#	$(CC) -o libconftest.so -shared $(srcdir)/dltest.c
