F77INCLUDES = -I. -I../attr
DEPADD = @MPILIBLOC@ ../util/mtestf.o
smvar_do_sharedlibs = 0

F77HEADERS = addsize.h

# allocmem_SOURCES = allocmem.f
winscale1f_SOURCES = winscale1f.f
winscale1f_LDADD   = ../util/mtestf.o
winscale2f_SOURCES = winscale2f.f
winscale2f_LDADD   = ../util/mtestf.o
winfencef_SOURCES  = winfencef.f
winfencef_LDADD    = ../util/mtestf.o
wingetf_SOURCES    = wingetf.f
wingetf_LDADD      = ../util/mtestf.o
winerrf_SOURCES    = winerrf.f
winerrf_LDADD      = ../util/mtestf.o
winnamef_SOURCES   = winnamef.f
winnamef_LDADD     = ../util/mtestf.o
wingroupf_SOURCES  = wingroupf.f
wingroupf_LDADD    = ../util/mtestf.o
winaccf_SOURCES    = winaccf.f
winaccf_LDADD      = ../util/mtestf.o

c2f2cwinf_SOURCES = c2f2cwin.c c2f2cwinf.f
c2f2cwinf_LDADD   = ../util/mtestf.o 

baseattrwinf_SOURCES  = baseattrwinf.f
baseattrwinf_LDADD    = ../util/mtestf.o
winattrf_SOURCES      = winattrf.f
winattrf_LDADD        = ../util/mtestf.o
winattr2f_SOURCES     = winattr2f.f
winattr2f_LDADD       = ../util/mtestf.o

# bindir may be used in MPIEXEC, so make sure it is defined
BINDIR=${bindir}
testing:
	../../runtests -srcdir=$(srcdir) -tests=testlist \
			-mpiexec=@MPIEXEC@ \
		   	-xmlfile=summary.xml

../util/mtestf.o: 
	(cd ../util && $(MAKE) mtestf.o)
