INCLUDES = -I../../include -I${srcdir}/../../include
LDADD = ../../util/mtest.o
threaded_sr_LDADD = -lpthread 
DEPADD = @MPILIBLOC@ ../../util/mtest.o ../util/mtestthread.o
smvar_do_sharedlibs = 0

# Use extra programs to list programs that should not be built by default.
EXTRA_PROGRAMS       = 

threaded_sr_SOURCES  = threaded_sr.c
alltoall_SOURCES     = alltoall.c
sendselfth_SOURCES   = sendselfth.c
greq_wait_SOURCES    = greq_wait.c
greq_test_SOURCES    = greq_test.c
multisend_SOURCES    = multisend.c
multisend2_SOURCES   = multisend2.c
multisend2_LDADD = ../util/mtestthread.o
multisend3_SOURCES   = multisend3.c
multisend3_LDADD = ../util/mtestthread.o
multisend4_SOURCES   = multisend4.c
multisend4_LDADD = ../util/mtestthread.o

../../util/mtest.o:
	(cd ../../util && $(MAKE) mtest.o)
../util/mtestthread.o:
	(cd ../util && $(MAKE) mtestthread.o)

# A special testing target to simplify running just the thread pt2pt tests
testing:
	../../runtests -srcdir=$(srcdir) -tests=testlist \
		   -mpiexec=$(bindir)/mpiexec \
		   -xmlfile=summary.xml
