INCLUDES = -I../../include -I${srcdir}/../../include
#LDADD = ../../util/mtest.o
#DEPADD = @MPILIBLOC@ ../../util/mtest.o
smvar_do_sharedlibs = 0

# Use extra programs to list programs that should not be built by default.
EXTRA_PROGRAMS       = 

initth_SOURCES  = initth.c

../../util/mtest.o:
	(cd ../../util && $(MAKE) mtest.o)

# A special testing target to simplify running just the thread init tests
testing:
	../../runtests -srcdir=$(srcdir) -tests=testlist \
		   -mpiexec=$(bindir)/mpiexec \
		   -xmlfile=summary.xml
