INCLUDES = -I../../include -I${srcdir}/../../include
LDADD = ../util/mtest.o 
DEPADD = @MPILIBLOC@ ../util/mtest.o
smvar_do_sharedlibs = 0

attrtx_SOURCES = attrtx.cxx
attricx_SOURCES = attricx.cxx
#attrerrx_SOURCES = attrerrx.cxx
#attrerrcommx_SOURCES = attrerrcommx.cxx
#attrerrtypex_SOURCES = attrerrtypex.cxx
#attrorderx_SOURCES = attrorderx.cxx
#attrordercommx_SOURCES = attrordercommx.cxx
#attrordertypex_SOURCES = attrordertypex.cxx
#attrorderwinx_SOURCES = attrorderwinx.cxx
#baseattr2x_SOURCES = baseattr2x.cxx
baseattrcommx_SOURCES = baseattrcommx.cxx
#baseattrwinx_SOURCES = baseattrwinx.cxx
fkeyvalcommx_SOURCES = fkeyvalcommx.cxx
fkeyvaltypex_SOURCES = fkeyvaltypex.cxx

../util/mtest.o:
	(cd ../util && $(MAKE) mtest.o)
testing:
	../../runtests -srcdir=$(srcdir) -tests=testlist \
			-mpiexec=@MPIEXEC@ \
		   	-xmlfile=summary.xml
clean-local:
	-rm -f summary.xml
