#! /bin/sh
#
set -x
# This script builds a stand-alone DLL for the ssm channel.
# It makes use of the configure scripts in the necessary components
#
# Determine the source and build directory
mypath=$0
mypath=`echo $mypath | sed -e 's/builddll//'`
mympich2=`(cd $mypath && cd ../../../../.. && pwd)`
mybuild=`(cd ../../../../../ && pwd)`
#
echo "Building channel dll for ssm with $0"
#
# Get the prefix, libdir, and exec_prefix, which may be needed for
# setting installation directories.  These may be either passed on the
# command line or as environment variables
for arg do 
    option=`expr "x$arg" : 'x[^=]*=\(.*\)'`
    case $arg in 
        --prefix=*) prefix=$option
	;;
	--libdir=*) libdir=$option
	;;
	--exec-prefix=*) exec_prefix=$option
	;;
	--shlibtype=*) shlibtype=$option
	;;
	--localdefs=*) 
	if [ -s $option ] ; then 
	    . $option
	else
	    echo "File $option was not found"
	    exit 1
	fi
    esac
done
BUILD_DLLS=yes
export BUILD_DLLS
#
# Determine shared library type (only a few supported)
osname=`uname -s`
if [ -z "$shlibtype" ] ; then
    if [ -z "$CC" ] ; then
        shlibtype=gcc
    else
        shlibtype=$CC
    fi
    case $osname in
        *Darwin*|*darwin*)
         shlibtype="$shlibtype-osx"
        ;;
       *)
        ;;
    esac
fi

# Export the top_srcdir for MPICH2
master_top_srcdir=$mympich2
export master_top_srcdir
#
# Temp for experimentation
if [ -z "$CC_SHL" ] ; then
    case $shlibtype in
	gcc-osx|osx-gcc)
        CC_SHL="${CC} -fPIC"
        C_LINK_SHL='${CC} -dynamiclib -undefined suppress -single_module -flat_namespace'
        SHLIB_EXT=dylib
	;;
	*gcc*)
        CC_SHL="${CC} -fPIC"
        C_LINK_SHL='${CC} -shared'
        SHLIB_EXT=so
	;;
	*)
	echo "Unknown shared library type in builddll"
	exit 1
	;;
    esac
fi
export CC_SHL
export C_LINK_SHL
export SHLIB_EXT
#
CPPFLAGS="$CPPFLAGS -I$mympich2/src/mpid/ch3/include"
CPPFLAGS="$CPPFLAGS -I$mympich2/src/mpid/ch3/util/sock"
CPPFLAGS="$CPPFLAGS -I$mybuild/src/mpid/ch3/util/sock"

# The ssm channel requires the sock utilities in mpid/common/sock
# This directory may not exist yet (no other configure may have 
# created it), so we build it if necessary
if [ ! -d $mybuild/src/mpid/common/sock ] ; then 
    mkdir $mybuild/src/mpid/common/sock 
fi
(cd $mybuild/src/mpid/common/sock && \
    $mympich2/src/mpid/common/sock/configure --enable-sharedlibs=$shlibtype \
    --prefix=$prefix --libdir=$libdir --exec-prefix=$exec_prefix )
if [ $? != 0 ] ; then
    echo "Aborting build because mpi/common/sock/configure failed"
    echo "See $mybuild/src/mpid/common/sock/config.log for more information"
    exit 1
fi

# The ssm channel requires the lock utilities in mpid/common/locks
# This directory may not exist yet (no other configure may have 
# created it), so we build it if necessary
if [ ! -d $mybuild/src/mpid/common/locks ] ; then 
    mkdir $mybuild/src/mpid/common/locks
fi
# Note that we also need to run the setup in the locks directory
locksSetup=$mympich2/src/mpid/common/locks/setup
if [ ! -f $locksSetup ] ; then 
    echo "Cannot find $locksSetup , needed to build process locks"
    exit 1
fi
( \
CPPFLAGS="-I../../ch3/channels/ssm/include -I$mympich2/src/mpid/ch3/channels/ssm/include $CPPFLAGS" ; \
CPPFLAGS="$CPPFLAGS -I$mpmpich2/src/include -I../../../../src/include";\
CPPFLAGS="$CPPFLAGS -I$mympich2/src/mpid/common/datatype" ; \
CPPFLAGS="$CPPFLAGS -I../../ch3/channels/ssm/include" ; \
CPPFLAGS="$CPPFLAGS -I../../ch3/include" ; \
CPPFLAGS="$CPPFLAGS -DUSE_PROCESS_LOCKS" ; export CPPFLAGS ; \
  . $locksSetup ; \
cd $mybuild/src/mpid/common/locks && \
    $mympich2/src/mpid/common/locks/configure --enable-sharedlibs=$shlibtype \
    --prefix=$prefix --libdir=$libdir --exec-prefix=$exec_prefix )
if [ $? != 0 ] ; then
    echo "Aborting build because mpi/common/locks/configure failed"
    echo "See $mybuild/src/mpid/common/locks/config.log for more information"
    exit 1
fi

# Ensure that the sock channel includes are found before the dllchan includes
( \
CPPFLAGS="-I../../channels/ssm/include -I$mympich2/src/mpid/ch3/channels/ssm/include $CPPFLAGS";\
CPPFLAGS="$CPPFLAGS -I$mympich2/src/mpid/common/datatype" ; \
CPPFLAGS="$CPPFLAGS -I$mympich2/src/mpid/common/sock" ; \
CPPFLAGS="$CPPFLAGS -I$mympich2/src/mpid/common/sock/poll" ; \
CPPFLAGS="$CPPFLAGS -I../../../../common/sock" ; \
CPPFLAGS="$CPPFLAGS -I../../../../common/sock/poll" ; \
CPPFLAGS="$CPPFLAGS -I../include" ; \
CPPFLAGS="$CPPFLAGS -I../../../include" ; \
CPPFLAGS="$CPPFLAGS -I$mympich2/src/mpid/ch3/channels/ssm/include" ; \
CPPFLAGS="$CPPFLAGS -I../../../../common/locks" ; \
CPPFLAGS="$CPPFLAGS -I$mympich2/src/mpid/common/locks" ; \
CPPFLAGS="$CPPFLAGS -DUSE_PROCESS_LOCKS" ; export CPPFLAGS ; \
 $mypath/configure --enable-sharedlibs=$shlibtype \
    --prefix=$prefix --libdir=$libdir --exec-prefix=$exec_prefix )
#
# Make the channel library and update the channel dll
(cd src && make clean && rm -f libmpich2-ch3-ssm.la && \
    make libmpich2-ch3-ssm.la )
rc=$?
if [ $rc != 0 ] ; then
    echo "make step failed in ch3/channels/ssm/src"
    exit $rc
fi
rm -f *.lo
ar x src/libmpich2-ch3-ssm.la
ar cr libmpich2-ch3-ssm.la *.lo
rm -f *.lo
#
# Build the locks support code and link it into the ch3-ssm dll
(cd $mybuild/src/mpid/common/locks && make clean && \
    rm -f libmpich2locks.la && make libmpich2locks.la)
rc=$?
if [ $rc != 0 ] ; then
    echo "make step failed in common/locks"
    exit $rc
fi
mkdir .tmp
cd .tmp
rm -f *.lo
ar x $mybuild/src/mpid/common/locks/libmpich2locks.la
ar cr ../libmpich2-ch3-ssm.la *.lo
cd ..
rm -rf .tmp
#
# Build the ch3 shmbase support code and link it into the ch3-ssm dll
# Include the socket includes because they're needed by the ssm includes
# (at least for now)
#
# Build the ch3 shm support code and link it into the ch3-ssm dll
if [ ! -d ../../util ] ; then
    mkdir ../../util
fi
if [ ! -d ../../util/shmbase ] ; then
    mkdir ../../util/shmbase
fi
# Make sure the ssm include files are used ahead of the dllchan include files
(\
CPPFLAGS="-I../../channels/ssm/include -I$mympich2/src/mpid/ch3/channels/ssm/include $CPPFLAGS";\
CPPFLAGS="$CPPFLAGS -I$mympich2/src/mpid/common/sock" ; \
CPPFLAGS="$CPPFLAGS -I$mympich2/src/mpid/common/sock/poll" ; \
CPPFLAGS="$CPPFLAGS -I../../../common/sock" ; \
CPPFLAGS="$CPPFLAGS -I../../../common/sock/poll" ; \
CPPFLAGS="$CPPFLAGS -I../../channels/ssm/include" ; \
CPPFLAGS="$CPPFLAGS -I$mympich2/src/mpid/ch3/channels/ssm/include" ; \
CPPFLAGS="$CPPFLAGS -I../../include" ; \
CPPFLAGS="$CPPFLAGS -I$mympich2/src/mpid/ch3/include" ; \
CPPFLAGS="$CPPFLAGS -I$mympich2/src/mpid/common/datatype" ; \
CPPFLAGS="$CPPFLAGS -I../../../common/locks" ; \
CPPFLAGS="$CPPFLAGS -I$mympich2/src/mpid/common/locks" ; \
CPPFLAGS="$CPPFLAGS -DUSE_PROCESS_LOCKS" ; export CPPFLAGS ; \
cd ../../util/shmbase && \
    $mympich2/src/mpid/ch3/util/shmbase/configure \
    --enable-sharedlibs=$shlibtype \
    --prefix=$prefix --libdir=$libdir --exec-prefix=$exec_prefix )

(cd ../../util/shmbase && make clean && rm -f libmpich-shmutil.la && \
    make libmpich-shmutil.la)
rc=$?
if [ $rc != 0 ] ; then
    echo "make step failed in util/shmbase"
    exit $rc
fi
mkdir .tmp
cd .tmp
rm -f *.lo
ar x ../../../util/shmbase/libmpich-shmutil.la
ar cr ../libmpich2-ch3-ssm.la *.lo
cd ..
rm -rf .tmp
#
# Build the ch3 shm support code and link it into the ch3-ssm dll
# Include the socket includes because they're needed by the ssm includes
# (at least for now)
#
# Build the ch3 socket support code and link it into the ch3-ssm dll
if [ ! -d ../../util ] ; then
    mkdir ../../util
fi
if [ ! -d ../../util/shm ] ; then
    mkdir ../../util/shm
fi
# Make sure the shm include files are used ahead of the dllchan include files
(\
CPPFLAGS="-I../../channels/ssm/include -I$mympich2/src/mpid/ch3/channels/ssm/include $CPPFLAGS";\
CPPFLAGS="$CPPFLAGS -I$mympich2/src/mpid/common/sock" ; \
CPPFLAGS="$CPPFLAGS -I$mympich2/src/mpid/common/sock/poll" ; \
CPPFLAGS="$CPPFLAGS -I../../../common/sock" ; \
CPPFLAGS="$CPPFLAGS -I../../../common/sock/poll" ; \
CPPFLAGS="$CPPFLAGS -I../../channels/ssm/include" ; \
CPPFLAGS="$CPPFLAGS -I$mympich2/src/mpid/ch3/channels/ssm/include" ; \
CPPFLAGS="$CPPFLAGS -I../../include" ; \
CPPFLAGS="$CPPFLAGS -I$mympich2/src/mpid/ch3/include" ; \
CPPFLAGS="$CPPFLAGS -I$mympich2/src/mpid/common/datatype" ; \
CPPFLAGS="$CPPFLAGS -I../../../common/locks" ; \
CPPFLAGS="$CPPFLAGS -I$mympich2/src/mpid/common/locks" ; \
CPPFLAGS="$CPPFLAGS -DUSE_PROCESS_LOCKS" ; export CPPFLAGS ; \
cd ../../util/shm && \
    $mympich2/src/mpid/ch3/util/shm/configure \
    --enable-sharedlibs=$shlibtype \
    --prefix=$prefix --libdir=$libdir --exec-prefix=$exec_prefix )

(cd ../../util/shm && make clean && rm -f libmpich-sshmutil.la && \
    make libmpich-sshmutil.la)
rc=$?
if [ $rc != 0 ] ; then
    echo "make step failed in util/shm"
    exit $rc
fi
mkdir .tmp
cd .tmp
rm -f *.lo
ar x ../../../util/shm/libmpich-sshmutil.la
ar cr ../libmpich2-ch3-ssm.la *.lo
cd ..
rm -rf .tmp
#
# Build the socket support code and link it into the ch3-ssm dll
(cd $mybuild/src/mpid/common/sock/poll && make clean && \
    rm -f libmpich2sock.la && make libmpich2sock.la)
rc=$?
if [ $rc != 0 ] ; then
    echo "make step failed in common/sock/poll"
    exit $rc
fi
mkdir .tmp
cd .tmp
rm -f *.lo
ar x $mybuild/src/mpid/common/sock/poll/libmpich2sock.la
ar cr ../libmpich2-ch3-ssm.la *.lo
cd ..
rm -rf .tmp
#
# Build the ch3 socket support code and link it into the ch3-ssm dll
if [ ! -d ../../util ] ; then
    mkdir ../../util
fi
if [ ! -d ../../util/sock ] ; then
    mkdir ../../util/sock
fi

(\
CPPFLAGS="-I../../channels/ssm/include -I$mympich2/src/mpid/ch3/channels/ssm/include $CPPFLAGS" ; \
CPPFLAGS="$CPPFLAGS -I$mympich2/src/mpid/common/sock" ; \
CPPFLAGS="$CPPFLAGS -I$mympich2/src/mpid/common/sock/poll" ; \
CPPFLAGS="$CPPFLAGS -I../../../common/sock" ; \
CPPFLAGS="$CPPFLAGS -I../../../common/sock/poll" ; \
CPPFLAGS="$CPPFLAGS -I../../include" ; \
CPPFLAGS="$CPPFLAGS -I$mympich2/src/mpid/ch3/include" ; \
CPPFLAGS="$CPPFLAGS -I$mympich2/src/mpid/common/datatype" ;\
CPPFLAGS="$CPPFLAGS -I../../../common/locks" ; \
CPPFLAGS="$CPPFLAGS -I$mympich2/src/mpid/common/locks" ; \
CPPFLAGS="$CPPFLAGS -DUSE_PROCESS_LOCKS" ; export CPPFLAGS ; \
cd ../../util/sock && \
    $mympich2/src/mpid/ch3/util/sock/configure --enable-sharedlibs=$shlibtype \
    --prefix=$prefix --libdir=$libdir --exec-prefix=$exec_prefix )

(cd ../../util/sock && make clean && rm -f libmpich-sockutil.la && \
    make libmpich-sockutil.la)
rc=$?
if [ $rc != 0 ] ; then
    echo "make step failed in util/sock"
    exit $rc
fi
mkdir .tmp
cd .tmp
rm -f *.lo
ar x ../../../util/sock/libmpich-sockutil.la
ar cr ../libmpich2-ch3-ssm.la *.lo
cd ..
rm -rf .tmp

#
# Now, create the dynamically-loadable library
rm -f libmpich2-ch3-ssm*.dylib libmpich2-ch3-ssm*.so
$mybuild/src/util/createshlib -echo --mode=link -version-info "1:1" \
    -clink="$C_LINK_SHL" -cc=gcc -libtype=$shlibtype \
    -o libmpich2-ch3-ssm.la -rpath `pwd`
rc=$?
if [ $rc != 0 ] ; then 
    echo "Createshlib step failed for ssm channel"
    exit $rc
fi
# Note that when this directory is installed, it needs to be rebuilt with 
# a different rpath.
