#! /bin/sh
# Let the ch3 configure know which utility modules are needed for this channel
# (in ch3/util/<directory>, in this case, ch3/util/sock and shm because
# this channel uses both sockets and shared memory)
ch3subsystems="$ch3subsystems sock shm shmbase"
needs_sock=yes
needs_shm=yes
needs_shmbase=yes
