INCLUDES = -I../include -I${srcdir}/../include
LDADD = 
DEPADD = @MPILIBLOC@
smvar_do_sharedlibs = 0

# The allmpi program uses MPICH internal header files
EXTRA_PROGRAMS = allmpi

self_SOURCES = self.c
simple_SOURCES = simple.c
sendrecv_SOURCES = sendrecv.c
srtest_SOURCES = srtest.c
wtime_SOURCES = wtime.c
netpipe_SOURCES = netmpi.c GetOpt.c
patterns_SOURCES = patterns.c
adapt_SOURCES = adapt.c GetOpt.c
allmpi_SOURCES = allmpi.c
