#sctp_dir = $(SCTP_LOC)
#INCLUDES = -I../../../../../include -I${master_top_srcdir}/src/include -I$(sctp_dir)/include
INCLUDES = -I../../../../../include -I${master_top_srcdir}/src/include 
#LIBS = -L$(SCTP_LOC)/lib -lsctp
lib${MPILIBNAME}_a_SOURCES =			\
    sctp_common.c				\
    all_hash.c					\
    sctp_util.c					\
    ch3_finalize.c				\
    ch3_init.c					\
    ch3_isend.c					\
    ch3_isendv.c				\
    ch3_istartmsg.c				\
    ch3_istartmsgv.c				\
    ch3_progress.c
