F77INCLUDES = -I.
LDADD = ../util/mtestf.o 
DEPADD = @MPILIBLOC@ ../util/mtestf.o
smvar_do_sharedlibs = 0

statusesf_SOURCES = statusesf.f
greqf_SOURCES     = greqf.f dummyf.f

testing:
	../../runtests -srcdir=$(srcdir) -tests=testlist \
			-mpiexec=$(bindir)/mpiexec \
		   	-xmlfile=summary.xml
../util/mtestf.o: 
	(cd ../util && $(MAKE) mtestf.o)
