noinst_PROGRAMS += accfence1                       \
                   accpscw1                        \
                   epochtest                       \
                   getfence1                       \
                   lock_contention_dt              \
                   lock_dt                         \
                   lock_dt_flush                   \
                   lock_dt_flushlocal              \
                   lockall_dt                      \
                   lockall_dt_flush                \
                   lockall_dt_flushall             \
                   lockall_dt_flushlocal           \
                   lockall_dt_flushlocalall        \
                   putfence1                       \
                   putpscw1                        \
                   accfence1_struct                \
                   accpscw1_struct                 \
                   epochtest_struct                \
                   getfence1_struct                \
                   lock_contention_dt_struct       \
                   lock_dt_struct                  \
                   lock_dt_flush_struct            \
                   lock_dt_flushlocal_struct       \
                   lockall_dt_struct               \
                   lockall_dt_flush_struct         \
                   lockall_dt_flushall_struct      \
                   lockall_dt_flushlocal_struct    \
                   lockall_dt_flushlocalall_struct \
                   putfence1_struct                \
                   putpscw1_struct


accfence1_CPPFLAGS = $(AM_CPPFLAGS)
accfence1_SOURCES = accfence1.c

accpscw1_CPPFLAGS = $(AM_CPPFLAGS)
accpscw1_SOURCES = accpscw1.c

epochtest_CPPFLAGS = $(AM_CPPFLAGS)
epochtest_SOURCES = epochtest.c

getfence1_CPPFLAGS = $(AM_CPPFLAGS)
getfence1_SOURCES = getfence1.c

lock_contention_dt_CPPFLAGS = -DMULTI_ORIGIN -DSINGLE_TARGET -DUSE_FLUSH_NONE -DUSE_FLUSH_LOCAL_NONE $(AM_CPPFLAGS)
lock_contention_dt_SOURCES = lock_x_dt.c

lock_dt_CPPFLAGS = -DSINGLE_ORIGIN -DSINGLE_TARGET -DUSE_FLUSH_NONE -DUSE_FLUSH_LOCAL_NONE $(AM_CPPFLAGS)
lock_dt_SOURCES = lock_x_dt.c

lock_dt_flush_CPPFLAGS = -DSINGLE_ORIGIN -DSINGLE_TARGET -DUSE_FLUSH -DUSE_FLUSH_LOCAL_NONE $(AM_CPPFLAGS)
lock_dt_flush_SOURCES = lock_x_dt.c

lock_dt_flushlocal_CPPFLAGS = -DSINGLE_ORIGIN -DSINGLE_TARGET -DUSE_FLUSH_NONE -DUSE_FLUSH_LOCAL $(AM_CPPFLAGS)
lock_dt_flushlocal_SOURCES = lock_x_dt.c

lockall_dt_CPPFLAGS = -DSINGLE_ORIGIN -DMULTI_TARGET -DUSE_FLUSH_NONE -DUSE_FLUSH_LOCAL_NONE $(AM_CPPFLAGS)
lockall_dt_SOURCES = lock_x_dt.c

lockall_dt_flush_CPPFLAGS = -DSINGLE_ORIGIN -DMULTI_TARGET -DUSE_FLUSH -DUSE_FLUSH_LOCAL_NONE $(AM_CPPFLAGS)
lockall_dt_flush_SOURCES = lock_x_dt.c

lockall_dt_flushall_CPPFLAGS = -DSINGLE_ORIGIN -DMULTI_TARGET -DUSE_FLUSH_ALL -DUSE_FLUSH_LOCAL_NONE $(AM_CPPFLAGS)
lockall_dt_flushall_SOURCES = lock_x_dt.c

lockall_dt_flushlocal_CPPFLAGS = -DSINGLE_ORIGIN -DMULTI_TARGET -DUSE_FLUSH_NONE -DUSE_FLUSH_LOCAL $(AM_CPPFLAGS)
lockall_dt_flushlocal_SOURCES = lock_x_dt.c

lockall_dt_flushlocalall_CPPFLAGS = -DSINGLE_ORIGIN -DMULTI_TARGET -DUSE_FLUSH_NONE -DUSE_FLUSH_LOCAL_ALL $(AM_CPPFLAGS)
lockall_dt_flushlocalall_SOURCES = lock_x_dt.c

putfence1_CPPFLAGS = $(AM_CPPFLAGS)
putfence1_SOURCES = putfence1.c

putpscw1_CPPFLAGS = $(AM_CPPFLAGS)
putpscw1_SOURCES = putpscw1.c

accfence1_struct_CPPFLAGS = -DUSE_DTP_POOL_TYPE__STRUCT $(AM_CPPFLAGS)
accfence1_struct_SOURCES = accfence1.c

accpscw1_struct_CPPFLAGS = -DUSE_DTP_POOL_TYPE__STRUCT FLAGS)
accpscw1_struct_SOURCES = accpscw1.c

epochtest_struct_CPPFLAGS = -DUSE_DTP_POOL_TYPE__STRUCT $(AM_CPPFLAGS)
epochtest_struct_SOURCES = epochtest.c

getfence1_struct_CPPFLAGS = -DUSE_DTP_POOL_TYPE__STRUCT $(AM_CPPFLAGS)
getfence1_struct_SOURCES = getfence1.c

lock_contention_dt_struct_CPPFLAGS = -DUSE_DTP_POOL_TYPE__STRUCT -DLOCK_CONTENTION_DT $(AM_CPPFLAGS)
lock_contention_dt_struct_SOURCES = lock_x_dt.c

lock_dt_struct_CPPFLAGS = -DUSE_DTP_POOL_TYPE__STRUCT -DLOCK_DT $(AM_CPPFLAGS)
lock_dt_struct_SOURCES = lock_x_dt.c

lock_dt_flush_struct_CPPFLAGS = -DUSE_DTP_POOL_TYPE__STRUCT -DLOCK_DT_FLUSH $(AM_CPPFLAGS)
lock_dt_flush_struct_SOURCES = lock_x_dt.c

lock_dt_flushlocal_struct_CPPFLAGS = -DUSE_DTP_POOL_TYPE__STRUCT -DLOCK_DT_FLUSHLOCAL $(AM_CPPFLAGS)
lock_dt_flushlocal_struct_SOURCES = lock_x_dt.c

lockall_dt_struct_CPPFLAGS = -DUSE_DTP_POOL_TYPE__STRUCT -DLOCKALL_DT $(AM_CPPFLAGS)
lockall_dt_struct_SOURCES = lock_x_dt.c

lockall_dt_flush_struct_CPPFLAGS = -DUSE_DTP_POOL_TYPE__STRUCT -DLOCKALL_DT_FLUSH $(AM_CPPFLAGS)
lockall_dt_flush_struct_SOURCES = lock_x_dt.c

lockall_dt_flushall_struct_CPPFLAGS = -DUSE_DTP_POOL_TYPE__STRUCT -DLOCKALL_DT_FLUSHALL $(AM_CPPFLAGS)
lockall_dt_flushall_struct_SOURCES = lock_x_dt.c

lockall_dt_flushlocal_struct_CPPFLAGS = -DUSE_DTP_POOL_TYPE__STRUCT -DLOCKALL_DT_FLUSHLOCAL $(AM_CPPFLAGS)
lockall_dt_flushlocal_struct_SOURCES = lock_x_dt.c

lockall_dt_flushlocalall_struct_CPPFLAGS = -DUSE_DTP_POOL_TYPE__STRUCT -DLOCKALL_DT_FLUSHLOCALALL $(AM_CPPFLAGS)
lockall_dt_flushlocalall_struct_SOURCES = lock_x_dt.c

putfence1_struct_CPPFLAGS = -DUSE_DTP_POOL_TYPE__STRUCT $(AM_CPPFLAGS)
putfence1_struct_SOURCES = putfence1.c

putpscw1_struct_CPPFLAGS = -DUSE_DTP_POOL_TYPE__STRUCT $(AM_CPPFLAGS)
putpscw1_struct_SOURCES = putpscw1.c
