# LIBS includes -lmpich and other libraries (e.g., -lpmpich if
# weak symbols are not supported)
INCLUDES = -I../include -I${top_srcdir}/include
EXTERNAL_LIBS = m
LDADD = ../util/mtest.o
DEPADD = @MPILIBLOC@ ../util/mtest.o
smvar_do_sharedlibs = 0
#
allocmem_SOURCES = allocmem.c
ircpi_SOURCES = ircpi.c
ircpi_LDADD = -lm
test1_SOURCES = test1.c
test2_SOURCES = test2.c
test3_SOURCES = test3.c
test4_SOURCES = test4.c
test5_SOURCES = test5.c
lockcontention_SOURCES = lockcontention.c
lockcontention2_SOURCES = lockcontention2.c
locknull_SOURCES = locknull.c
wintest_SOURCES = wintest.c
transpose1_SOURCES = transpose1.c
transpose2_SOURCES = transpose2.c
transpose3_SOURCES = transpose3.c
transpose4_SOURCES = transpose4.c
transpose5_SOURCES = transpose5.c
transpose6_SOURCES = transpose6.c
transpose7_SOURCES = transpose7.c
fetchandadd_SOURCES = fetchandadd.c
fetchandadd_tree_SOURCES = fetchandadd_tree.c

winname_SOURCES = winname.c
putfence1_SOURCES = putfence1.c
putfidx_SOURCES   = putfidx.c
epochtest_SOURCES = epochtest.c
getfence1_SOURCES = getfence1.c
accfence1_SOURCES = accfence1.c
accfence2_SOURCES = accfence2.c
adlb_mimic1_SOURCES = adlb_mimic1.c
putpscw1_SOURCES = putpscw1.c
getgroup_SOURCES = getgroup.c
contig_displ_SOURCES = contig_displ.c

test1_am_SOURCES = test1_am.c
test2_am_SOURCES = test2_am.c
test3_am_SOURCES = test3_am.c
test4_am_SOURCES = test4_am.c
test5_am_SOURCES = test5_am.c
fetchandadd_am_SOURCES = fetchandadd_am.c
fetchandadd_tree_am_SOURCES = fetchandadd_tree_am.c
accfence2_am_SOURCES = accfence2_am.c

test1_dt_SOURCES = test1_dt.c

attrorderwin_SOURCES = attrorderwin.c
wincall_SOURCES = wincall.c
fkeyvalwin_SOURCES = fkeyvalwin.c 
baseattrwin_SOURCES = baseattrwin.c

nullpscw_SOURCES = nullpscw.c
rmanull_SOURCES    = rmanull.c

mixedsync_SOURCES = mixedsync.c
selfrma_SOURCES   = selfrma.c

strided_acc_onelock_SOURCES    = strided_acc_onelock.c
strided_putget_indexed_SOURCES = strided_putget_indexed.c
strided_acc_indexed_SOURCES    = strided_acc_indexed.c
strided_acc_subarray_SOURCES   = strided_acc_subarray.c
strided_get_indexed_SOURCES    = strided_get_indexed.c
window_creation_SOURCES        = window_creation.c
contention_put_SOURCES         = contention_put.c
contention_putget_SOURCES      = contention_putget.c

put_base_SOURCES   = put_base.c
put_bottom_SOURCES = put_bottom.c

../util/mtest.o:
	(cd ../util && $(MAKE) )

# A special testing target to simplify running just the rma tests
testing:
	../runtests -srcdir=$(srcdir) -tests=testlist \
		   -mpiexec=@MPIEXEC@ \
		   -xmlfile=summary.xml
