noinst_PROGRAMS += bcast bcast_comm_world_only bcast_struct

bcast_CPPFLAGS = $(AM_CPPFLAGS)
bcast_SOURCES = bcast.c

bcast_comm_world_only_CPPFLAGS = -DBCAST_COMM_WORLD_ONLY $(AM_CPPFLAGS)
bcast_comm_world_only_SOURCES = bcast.c

bcast_struct_CPPFLAGS = -DUSE_DTP_POOL_TYPE__STRUCT $(AM_CPPFLAGS)
bcast_struct_SOURCES = bcast.c
