.TH "hwloc_obj_attr_u::hwloc_memory_attr_s" 3 "9 Oct 2009" "Version 0.9.1rc1" "Hardware Locality (hwloc)" \" -*- nroff -*-
.ad l
.nh
.SH NAME
hwloc_obj_attr_u::hwloc_memory_attr_s \- Node-specific Object Attributes.  

.PP
.SH SYNOPSIS
.br
.PP
\fC#include <hwloc.h>\fP
.PP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "unsigned long \fBmemory_kB\fP"
.br
.RI "\fISize of memory node. \fP"
.ti -1c
.RI "unsigned long \fBhuge_page_free\fP"
.br
.RI "\fINumber of available huge pages. \fP"
.in -1c
.SH "Detailed Description"
.PP 
Node-specific Object Attributes. 
.SH "Field Documentation"
.PP 
.SS "unsigned long \fBhwloc_obj_attr_u::hwloc_memory_attr_s::huge_page_free\fP"
.PP
Number of available huge pages. 
.PP
.SS "unsigned long \fBhwloc_obj_attr_u::hwloc_memory_attr_s::memory_kB\fP"
.PP
Size of memory node. 
.PP


.SH "Author"
.PP 
Generated automatically by Doxygen for Hardware Locality (hwloc) from the source code.
