.TH "Topology Objects" 3 "9 Oct 2009" "Version 0.9.1rc1" "Hardware Locality (hwloc)" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Topology Objects \- 
.SS "Data Structures"

.in +1c
.ti -1c
.RI "struct \fBhwloc_obj\fP"
.br
.RI "\fIStructure of a topology object. \fP"
.ti -1c
.RI "union \fBhwloc_obj_attr_u\fP"
.br
.RI "\fIObject type-specific Attributes. \fP"
.in -1c
.SS "Typedefs"

.in +1c
.ti -1c
.RI "typedef struct \fBhwloc_obj\fP * \fBhwloc_obj_t\fP"
.br
.in -1c
.SH "Typedef Documentation"
.PP 
.SS "typedef struct \fBhwloc_obj\fP* \fBhwloc_obj_t\fP"
.PP
.SH "Author"
.PP 
Generated automatically by Doxygen for Hardware Locality (hwloc) from the source code.
