INCLUDES = -I../include -I${srcdir}/../include
LDADD = ../util/mtest.o
DEPADD = @MPILIBLOC@ ../util/mtest.o
smvar_do_sharedlibs = 0

attrt_SOURCES = attrt.c
attrend_SOURCES = attrend.c
attrend2_SOURCES = attrend2.c
attric_SOURCES = attric.c
attrerr_SOURCES = attrerr.c
attrerrcomm_SOURCES = attrerrcomm.c
attrerrtype_SOURCES = attrerrtype.c
attr2type_SOURCES = attr2type.c
attrorder_SOURCES = attrorder.c
attrordercomm_SOURCES = attrordercomm.c
attrordertype_SOURCES = attrordertype.c
baseattr2_SOURCES = baseattr2.c
baseattrcomm_SOURCES = baseattrcomm.c
fkeyval_SOURCES = fkeyval.c
fkeyvalcomm_SOURCES = fkeyvalcomm.c
fkeyvaltype_SOURCES = fkeyvaltype.c
keyval_double_free_SOURCES = keyval_double_free.c

../util/mtest.o:
	(cd ../util && $(MAKE) mtest.o)
testing:
	../runtests -srcdir=$(srcdir) -tests=testlist \
			-mpiexec=@MPIEXEC@ \
		   	-xmlfile=summary.xml
clean-local:
	-rm -f summary.xml
