# SUBDIRS_device_name are the names that @ devicename @ can take in SUBDIRS
SUBDIRS_device_name = mm ch3 rdma globus
SUBDIRS = @device_name@ common .
# Remove PMPILIBNAME from the common make variables for the mpid
# directories
smvarSubdir_commonmake=MPILIBNAME      = @MPILIBNAME@
