# SUBDIRS_device_name are the names that @ devicename @ can take in SUBDIRS
SUBDIRS_device_name = ch3 globus dcmfd
SUBDIRS = common @device_name@ .
# Remove PMPILIBNAME from the common make variables for the mpid
# directories
smvarSubdir_commonmake=MPILIBNAME      = @MPILIBNAME@
