EXTRA_DIRS = ../../../common/locks
SUBDIRS = src .

distclean-local:
	-rm -f include/mpidi_ch3i_shm_conf.h

maintainer-clean-local:
	-rm -f include/mpidi_ch3i_shm_conf.h.in

optinstall_DLLLIB = libmpich2-ch3-shm.@SHLIB_EXT@
