INCLUDES = -I../include -I${srcdir}/../include
smvar_do_sharedlibs = 0

singjoin_SOURCES    = singjoin.c
testconnect_SOURCES = testconnect.c
testconnectserial_SOURCES = testconnectserial.c tchandlers.c tcutil.c
testconnectserial_LDADD = -lm
dimsbalanced_SOURCES = dimsbalanced.c

testconnectserial.o: testconnectserial.c
	$(C_COMPILE) -c -DMPICHLIBSTR=\"$(MPIDIR)\" $<

clean-local:
	@rm -f test-port
