F77INCLUDES = -I. 
DEPADD = @MPILIBLOC@ ../util/mtestf.o
smvar_do_sharedlibs = 0
F77HEADERS = iodisp.h iooffset.h

iwriteatf_SOURCES     = iwriteatf.f
iwriteatf_LDADD       = ../util/mtestf.o
iwritef_SOURCES       = iwritef.f
iwritef_LDADD         = ../util/mtestf.o
iwriteshf_SOURCES     = iwriteshf.f
iwriteshf_LDADD       = ../util/mtestf.o
writef_SOURCES        = writef.f
writef_LDADD          = ../util/mtestf.o
writeatf_SOURCES      = writeatf.f
writeatf_LDADD        = ../util/mtestf.o
writeallf_SOURCES     = writeallf.f
writeallf_LDADD       = ../util/mtestf.o
writeatallf_SOURCES   = writeatallf.f
writeatallf_LDADD     = ../util/mtestf.o
writeallbef_SOURCES   = writeallbef.f
writeallbef_LDADD     = ../util/mtestf.o
writeordf_SOURCES     = writeordf.f
writeordf_LDADD       = ../util/mtestf.o
writeordbef_SOURCES   = writeordbef.f
writeordbef_LDADD     = ../util/mtestf.o
writeshf_SOURCES      = writeshf.f
writeshf_LDADD        = ../util/mtestf.o
writeatallbef_SOURCES = writeatallbef.f
writeatallbef_LDADD   = ../util/mtestf.o

fileerrf_SOURCES      = fileerrf.f
fileerrf_LDADD        = ../util/mtestf.o
fileinfof_SOURCES     = fileinfof.f
fileinfof_LDADD       = ../util/mtestf.o
shpositionf_SOURCES   = shpositionf.f
shpositionf_LDADD     = ../util/mtestf.o

atomicityf_SOURCES    = atomicityf.f
miscfilef_SOURCES     = miscfilef.f
miscfilef_LDADD     = ../util/mtestf.o

setviewcurf_SOURCES   = setviewcurf.f
setviewcurf_LDADD     = ../util/mtestf.o

c2fmultio_SOURCES     = c2fmultio.c
c2f2ciof_SOURCES      = c2f2cio.c c2f2ciof.f
c2f2ciof_LDADD        = ../util/mtestf.o 

# These IO tests are build from a template and a set of definitions.
iwriteatf.f writef.f writeatf.f writeatallf.f writeallf.f writeallbef.f \
writeordf.f writeordbef.f writeshf.f writeatallbef.f \
iwritef.f iwriteshf.f : ioharness.tlt ioharness.defn ../../maint/testmerge
	../../maint/testmerge -defn=$(top_srcdir)/maint/common.defn \
		$(srcdir)/ioharness.defn $(srcdir)/ioharness.tlt

testing:
	../../runtests -srcdir=$(srcdir) -tests=testlist \
			-mpiexec=$(bindir)/mpiexec \
		   	-xmlfile=summary.xml

../util/mtestf.o: 
	(cd ../util && $(MAKE) mtestf.o)

clean-local:
	rm -f .iotest.txt.*
