INCLUDES = -I../../include -I${srcdir}/../../include
LDADD = ../util/mtest.o 
DEPADD = @MPILIBLOC@ ../util/mtest.o
smvar_do_sharedlibs = 0

iwriteatx_SOURCES     = iwriteatx.cxx
iwritex_SOURCES       = iwritex.cxx
iwriteshx_SOURCES     = iwriteshx.cxx
writex_SOURCES        = writex.cxx
writeatx_SOURCES      = writeatx.cxx
writeallx_SOURCES     = writeallx.cxx
writeatallx_SOURCES   = writeatallx.cxx
writeallbex_SOURCES   = writeallbex.cxx
writeordx_SOURCES     = writeordx.cxx
writeordbex_SOURCES   = writeordbex.cxx
writeshx_SOURCES      = writeshx.cxx
writeatallbex_SOURCES = writeatallbex.cxx

iwriteatnosx_SOURCES     = iwriteatnosx.cxx
iwritenosx_SOURCES       = iwritenosx.cxx
iwriteshnosx_SOURCES     = iwriteshnosx.cxx
writenosx_SOURCES        = writenosx.cxx
writeatnosx_SOURCES      = writeatnosx.cxx
writeallnosx_SOURCES     = writeallnosx.cxx
writeatallnosx_SOURCES   = writeatallnosx.cxx
writeallbenosx_SOURCES   = writeallbenosx.cxx
writeordnosx_SOURCES     = writeordnosx.cxx
writeordbenosx_SOURCES   = writeordbenosx.cxx
writeshnosx_SOURCES      = writeshnosx.cxx
writeatallbenosx_SOURCES = writeatallbenosx.cxx


fileerrx_SOURCES      = fileerrx.cxx
fileinfox_SOURCES     = fileinfox.cxx
shpositionx_SOURCES   = shpositionx.cxx
setinfox_SOURCES      = setinfox.cxx
filemiscx_SOURCES     = filemiscx.cxx
seekavail_SOURCES     = seekavail.cxx
# These IO tests are built from a template and a set of definitions.
iwriteatx.cxx writex.cxx writeatx.cxx writeatallx.cxx writeallx.cxx \
writeallbex.cxx writeordx.cxx writeordbex.cxx writeshx.cxx \
writeatallbex.cxx iwritex.cxx iwriteshx.cxx \
iwriteatnosx.cxx iwritenosx.cxx iwriteshnosx.cxx writenosx.cxx \
writeatnosx.cxx writeallnosx.cxx writeatallnosx.cxx writeallbenosx.cxx \
writeordnosx.cxx writeordbenosx.cxx writeshnosx.cxx \
writeatallbenosx.cxx : ioharness.tlt ioharness.defn
	../../maint/testmerge -defn=$(top_srcdir)/maint/common.defn \
		$(srcdir)/ioharness.defn $(srcdir)/ioharness.tlt

../util/mtest.o: 
	(cd ../util && $(MAKE) mtest.o)

clean-local:
	rm -f .iotest.txt.*
