## -*- Mode: Makefile; -*-
## vim: set ft=automake :
##
## (C) 2011 by Argonne National Laboratory.
##     See COPYRIGHT in top-level directory.
##

## This is an automake makefile fragment that should be included by:
##
##   include $(top_srcdir)/Makefile.mtest
##
## This makefile is for single-threaded tests.

include $(top_srcdir)/Makefile_common.mtest