#! /bin/sh
#
# Provide information to the top level configure about the capabilities of
# the ch3 device.  
#
# Currently, this is restricted to allowing the channels to assert 
# support for MPI_THREAD_MULTIPLE
#
# Get the channel from the device_args, and invoke any channel prereq
echo "Executing mpich2prereq in $devicedir with $device_args"
channel_name=`echo ${device_args} | sed -e 's/:.*$//'`
if test -z "$channel_name" ; then 
    channel_name=nemesis
fi
if test -n "$channel_name" ; then
    if test -f "$devicedir/channels/$channel_name/mpich2prereq" ; then
        . $devicedir/channels/$channel_name/mpich2prereq
    fi
fi
# Set a value for the maximum processor name.  If necessary, this script
# should run whatever tests are needed to determine the supported value.
MPID_MAX_PROCESSOR_NAME=128
