SUBDIRS= .
INCLUDES = -I${master_top_srcdir}/src/include -I${top_builddir}/src/include
lib${MPILIBNAME}_a_SOURCES = \
mpid_rma_common.c \
mpid_win_create.c \
mpid_win_fence.c \
mpid_win_pscw.c \
mpid_win_lock.c \
mpid_put.c \
mpid_get.c \
mpid_accumulate.c \
mpid_misc.c \
mpid_onesided.h
