smvar_do_sharedlibs = 0
mtest.o: mtest.c
all-local: mtest.o
INCLUDES = -I${srcdir}/../include -I../include

# mtestcheck is used to check the mtest routines, particularly for
# storage leaks.
EXTRA_PROGRAMS = mtestcheck

mtestcheck_SOURCES = mtestcheck.c mtest.c

