smvar_do_sharedlibs = 0
mtest.o: mtest.c
all-local: mtest.o
INCLUDES = -I../../../src/include -I${top_srcdir}/src/include -I../include \
	 -I${srcdir}/../include

# mtestcheck is used to check the mtest routines, particularly for
# storage leaks.
EXTRA_PROGRAMS = mtestcheck

mtestcheck_SOURCES = mtestcheck.c mtest.c

