#!/usr/bin/perl
use strict;

my @extern_list;
my @internal_h;
open In, "mpi_abi.h" or die "Can't open mpi_abi.h: $!\n";
while(<In>){
    chomp;
    if (/MPI_ABI_H_INCLUDED/) {
    }
    elsif (/^extern struct \w+ abi_mpi_\w+;/) {
    }
    elsif (/^\s*int MPI_(SOURCE|TAG|ERROR);/) {
        push @internal_h, $_;
    }
    elsif (/^(int|double) (P?MPI\w+)\((.*)\);/) {
        my ($T, $name, $param) = ($1, $2, $3);
        $param=~s/\bMPI_/ABI_/g;
        push @internal_h, "$T $name($param) MPICH_API_PUBLIC;";
    }
    else {
        s/\bMPI_/ABI_/g;
        push @internal_h, $_;
    }
}
close In;
open Out, ">mpi_abi_internal.h" or die "Can't write mpi_abi_internal.h: $!\n";
print "  --> [mpi_abi_internal.h]\n";
print Out "/*\n";
print Out " * Copyright (C) by Argonne National Laboratory\n";
print Out " *     See COPYRIGHT in top-level directory\n";
print Out " */\n";
print Out "/* This file is automatically generated. DO NOT EDIT. */\n";
print Out "\n";
print Out "#ifndef MPI_ABI_INTERNAL_H_INCLUDED\n";
print Out "#define MPI_ABI_INTERNAL_H_INCLUDED\n";
print Out "\n";
print Out "/* hack to prevent inclusion of mpi_proto.h */\n";
print Out "#define MPI_PROTO_H_INCLUDED\n";
print Out "/* hack to prevent inclusion of mpio prototypes */\n";
print Out "#define HAVE_MPIO_PROTOTYPES\n";
print Out "enum QMPI_Functions_enum;\n";
print Out "#include \"mpichconf.h\"\n";
print Out "#include \"mpiimpl.h\"\n";
print Out "\n";
foreach my $l (@internal_h) {
    print Out "$l\n";
}
print Out "\n";
print Out "#endif /* MPI_ABI_INTERNAL_H_INCLUDED */\n";
close Out;
