/*
 * Copyright (C) by Argonne National Laboratory
 *     See COPYRIGHT in top-level directory
 */

#include "mpi_abi_internal.h"
#include "mpi_abi_util.h"

struct mpi_comm_t abi_mpi_comm_world MPICH_API_PUBLIC;
struct mpi_comm_t abi_mpi_comm_self MPICH_API_PUBLIC;
struct mpi_datatype_t abi_mpi_char MPICH_API_PUBLIC;
struct mpi_datatype_t abi_mpi_short MPICH_API_PUBLIC;
struct mpi_datatype_t abi_mpi_int MPICH_API_PUBLIC;
struct mpi_datatype_t abi_mpi_long MPICH_API_PUBLIC;
struct mpi_datatype_t abi_mpi_long_long_int MPICH_API_PUBLIC;
struct mpi_datatype_t abi_mpi_long_long MPICH_API_PUBLIC;
struct mpi_datatype_t abi_mpi_signed_char MPICH_API_PUBLIC;
struct mpi_datatype_t abi_mpi_unsigned_char MPICH_API_PUBLIC;
struct mpi_datatype_t abi_mpi_unsigned_short MPICH_API_PUBLIC;
struct mpi_datatype_t abi_mpi_unsigned MPICH_API_PUBLIC;
struct mpi_datatype_t abi_mpi_unsigned_long MPICH_API_PUBLIC;
struct mpi_datatype_t abi_mpi_unsigned_long_long MPICH_API_PUBLIC;
struct mpi_datatype_t abi_mpi_float MPICH_API_PUBLIC;
struct mpi_datatype_t abi_mpi_double MPICH_API_PUBLIC;
struct mpi_datatype_t abi_mpi_long_double MPICH_API_PUBLIC;
struct mpi_datatype_t abi_mpi_wchar MPICH_API_PUBLIC;
struct mpi_datatype_t abi_mpi_c_bool MPICH_API_PUBLIC;
struct mpi_datatype_t abi_mpi_int8_t MPICH_API_PUBLIC;
struct mpi_datatype_t abi_mpi_int16_t MPICH_API_PUBLIC;
struct mpi_datatype_t abi_mpi_int32_t MPICH_API_PUBLIC;
struct mpi_datatype_t abi_mpi_int64_t MPICH_API_PUBLIC;
struct mpi_datatype_t abi_mpi_uint8_t MPICH_API_PUBLIC;
struct mpi_datatype_t abi_mpi_uint16_t MPICH_API_PUBLIC;
struct mpi_datatype_t abi_mpi_uint32_t MPICH_API_PUBLIC;
struct mpi_datatype_t abi_mpi_uint64_t MPICH_API_PUBLIC;
struct mpi_datatype_t abi_mpi_aint MPICH_API_PUBLIC;
struct mpi_datatype_t abi_mpi_count MPICH_API_PUBLIC;
struct mpi_datatype_t abi_mpi_offset MPICH_API_PUBLIC;
struct mpi_datatype_t abi_mpi_c_complex MPICH_API_PUBLIC;
struct mpi_datatype_t abi_mpi_c_float_complex MPICH_API_PUBLIC;
struct mpi_datatype_t abi_mpi_c_double_complex MPICH_API_PUBLIC;
struct mpi_datatype_t abi_mpi_c_long_double_complex MPICH_API_PUBLIC;
struct mpi_datatype_t abi_mpi_byte MPICH_API_PUBLIC;
struct mpi_datatype_t abi_mpi_packed MPICH_API_PUBLIC;
struct mpi_datatype_t abi_mpi_integer MPICH_API_PUBLIC;
struct mpi_datatype_t abi_mpi_real MPICH_API_PUBLIC;
struct mpi_datatype_t abi_mpi_double_precision MPICH_API_PUBLIC;
struct mpi_datatype_t abi_mpi_complex MPICH_API_PUBLIC;
struct mpi_datatype_t abi_mpi_logical MPICH_API_PUBLIC;
struct mpi_datatype_t abi_mpi_character MPICH_API_PUBLIC;
struct mpi_datatype_t abi_mpi_cxx_bool MPICH_API_PUBLIC;
struct mpi_datatype_t abi_mpi_cxx_float_complex MPICH_API_PUBLIC;
struct mpi_datatype_t abi_mpi_cxx_double_complex MPICH_API_PUBLIC;
struct mpi_datatype_t abi_mpi_cxx_long_double_complex MPICH_API_PUBLIC;
struct mpi_datatype_t abi_mpi_double_complex MPICH_API_PUBLIC;
struct mpi_datatype_t abi_mpi_integer1 MPICH_API_PUBLIC;
struct mpi_datatype_t abi_mpi_integer2 MPICH_API_PUBLIC;
struct mpi_datatype_t abi_mpi_integer4 MPICH_API_PUBLIC;
struct mpi_datatype_t abi_mpi_integer8 MPICH_API_PUBLIC;
struct mpi_datatype_t abi_mpi_integer16 MPICH_API_PUBLIC;
struct mpi_datatype_t abi_mpi_real2 MPICH_API_PUBLIC;
struct mpi_datatype_t abi_mpi_real4 MPICH_API_PUBLIC;
struct mpi_datatype_t abi_mpi_real8 MPICH_API_PUBLIC;
struct mpi_datatype_t abi_mpi_real16 MPICH_API_PUBLIC;
struct mpi_datatype_t abi_mpi_complex4 MPICH_API_PUBLIC;
struct mpi_datatype_t abi_mpi_complex8 MPICH_API_PUBLIC;
struct mpi_datatype_t abi_mpi_complex16 MPICH_API_PUBLIC;
struct mpi_datatype_t abi_mpi_complex32 MPICH_API_PUBLIC;
struct mpi_datatype_t abi_mpi_float_int MPICH_API_PUBLIC;
struct mpi_datatype_t abi_mpi_double_int MPICH_API_PUBLIC;
struct mpi_datatype_t abi_mpi_long_int MPICH_API_PUBLIC;
struct mpi_datatype_t abi_mpi_2int MPICH_API_PUBLIC;
struct mpi_datatype_t abi_mpi_short_int MPICH_API_PUBLIC;
struct mpi_datatype_t abi_mpi_long_double_int MPICH_API_PUBLIC;
struct mpi_datatype_t abi_mpi_2real MPICH_API_PUBLIC;
struct mpi_datatype_t abi_mpi_2double_precision MPICH_API_PUBLIC;
struct mpi_datatype_t abi_mpi_2integer MPICH_API_PUBLIC;
struct mpi_errhandler_t abi_mpi_errors_are_fatal MPICH_API_PUBLIC;
struct mpi_errhandler_t abi_mpi_errors_abort MPICH_API_PUBLIC;
struct mpi_errhandler_t abi_mpi_errors_return MPICH_API_PUBLIC;
struct mpi_group_t abi_mpi_group_empty MPICH_API_PUBLIC;
struct mpi_info_t abi_mpi_info_env MPICH_API_PUBLIC;
struct mpi_message_t abi_mpi_message_no_proc MPICH_API_PUBLIC;
struct mpi_op_t abi_mpi_max MPICH_API_PUBLIC;
struct mpi_op_t abi_mpi_min MPICH_API_PUBLIC;
struct mpi_op_t abi_mpi_sum MPICH_API_PUBLIC;
struct mpi_op_t abi_mpi_prod MPICH_API_PUBLIC;
struct mpi_op_t abi_mpi_land MPICH_API_PUBLIC;
struct mpi_op_t abi_mpi_band MPICH_API_PUBLIC;
struct mpi_op_t abi_mpi_lor MPICH_API_PUBLIC;
struct mpi_op_t abi_mpi_bor MPICH_API_PUBLIC;
struct mpi_op_t abi_mpi_lxor MPICH_API_PUBLIC;
struct mpi_op_t abi_mpi_bxor MPICH_API_PUBLIC;
struct mpi_op_t abi_mpi_maxloc MPICH_API_PUBLIC;
struct mpi_op_t abi_mpi_minloc MPICH_API_PUBLIC;
struct mpi_op_t abi_mpi_replace MPICH_API_PUBLIC;
struct mpi_op_t abi_mpi_no_op MPICH_API_PUBLIC;

void ABI_init_builtins(void)
{
    abi_mpi_comm_world.handle = MPI_COMM_WORLD;
    abi_mpi_comm_self.handle = MPI_COMM_SELF;

    abi_mpi_char.handle = MPI_CHAR;
    abi_mpi_short.handle = MPI_SHORT;
    abi_mpi_int.handle = MPI_INT;
    abi_mpi_long.handle = MPI_LONG;
    abi_mpi_long_long_int.handle = MPI_LONG_LONG_INT;
    abi_mpi_long_long.handle = MPI_LONG_LONG;
    abi_mpi_signed_char.handle = MPI_SIGNED_CHAR;
    abi_mpi_unsigned_char.handle = MPI_UNSIGNED_CHAR;
    abi_mpi_unsigned_short.handle = MPI_UNSIGNED_SHORT;
    abi_mpi_unsigned.handle = MPI_UNSIGNED;
    abi_mpi_unsigned_long.handle = MPI_UNSIGNED_LONG;
    abi_mpi_unsigned_long_long.handle = MPI_UNSIGNED_LONG_LONG;
    abi_mpi_float.handle = MPI_FLOAT;
    abi_mpi_double.handle = MPI_DOUBLE;
    abi_mpi_long_double.handle = MPI_LONG_DOUBLE;
    abi_mpi_wchar.handle = MPI_WCHAR;
    abi_mpi_c_bool.handle = MPI_C_BOOL;
    abi_mpi_int8_t.handle = MPI_INT8_T;
    abi_mpi_int16_t.handle = MPI_INT16_T;
    abi_mpi_int32_t.handle = MPI_INT32_T;
    abi_mpi_int64_t.handle = MPI_INT64_T;
    abi_mpi_uint8_t.handle = MPI_UINT8_T;
    abi_mpi_uint16_t.handle = MPI_UINT16_T;
    abi_mpi_uint32_t.handle = MPI_UINT32_T;
    abi_mpi_uint64_t.handle = MPI_UINT64_T;
    abi_mpi_aint.handle = MPI_AINT;
    abi_mpi_count.handle = MPI_COUNT;
    abi_mpi_offset.handle = MPI_OFFSET;
    abi_mpi_c_complex.handle = MPI_C_COMPLEX;
    abi_mpi_c_float_complex.handle = MPI_C_FLOAT_COMPLEX;
    abi_mpi_c_double_complex.handle = MPI_C_DOUBLE_COMPLEX;
    abi_mpi_c_long_double_complex.handle = MPI_C_LONG_DOUBLE_COMPLEX;
    abi_mpi_byte.handle = MPI_BYTE;
    abi_mpi_packed.handle = MPI_PACKED;
    abi_mpi_integer.handle = MPI_INTEGER;
    abi_mpi_real.handle = MPI_REAL;
    abi_mpi_double_precision.handle = MPI_DOUBLE_PRECISION;
    abi_mpi_complex.handle = MPI_COMPLEX;
    abi_mpi_logical.handle = MPI_LOGICAL;
    abi_mpi_character.handle = MPI_CHARACTER;
    abi_mpi_cxx_bool.handle = MPI_CXX_BOOL;
    abi_mpi_cxx_float_complex.handle = MPI_CXX_FLOAT_COMPLEX;
    abi_mpi_cxx_double_complex.handle = MPI_CXX_DOUBLE_COMPLEX;
    abi_mpi_cxx_long_double_complex.handle = MPI_CXX_LONG_DOUBLE_COMPLEX;
    abi_mpi_double_complex.handle = MPI_DOUBLE_COMPLEX;
    abi_mpi_integer1.handle = MPI_INTEGER1;
    abi_mpi_integer2.handle = MPI_INTEGER2;
    abi_mpi_integer4.handle = MPI_INTEGER4;
    abi_mpi_integer8.handle = MPI_INTEGER8;
    abi_mpi_integer16.handle = MPI_INTEGER16;
    abi_mpi_real2.handle = MPI_DATATYPE_NULL;
    abi_mpi_real4.handle = MPI_REAL4;
    abi_mpi_real8.handle = MPI_REAL8;
    abi_mpi_real16.handle = MPI_REAL16;
    abi_mpi_complex4.handle = MPI_DATATYPE_NULL;
    abi_mpi_complex8.handle = MPI_COMPLEX8;
    abi_mpi_complex16.handle = MPI_COMPLEX16;
    abi_mpi_complex32.handle = MPI_COMPLEX32;
    abi_mpi_float_int.handle = MPI_FLOAT_INT;
    abi_mpi_double_int.handle = MPI_DOUBLE_INT;
    abi_mpi_long_int.handle = MPI_LONG_INT;
    abi_mpi_2int.handle = MPI_2INT;
    abi_mpi_short_int.handle = MPI_SHORT_INT;
    abi_mpi_long_double_int.handle = MPI_LONG_DOUBLE_INT;
    abi_mpi_2real.handle = MPI_2REAL;
    abi_mpi_2double_precision.handle = MPI_2DOUBLE_PRECISION;
    abi_mpi_2integer.handle = MPI_2INTEGER;

    abi_mpi_errors_are_fatal.handle = MPI_ERRORS_ARE_FATAL;
    abi_mpi_errors_abort.handle = MPI_ERRORS_ABORT;
    abi_mpi_errors_return.handle = MPI_ERRORS_RETURN;

    abi_mpi_group_empty.handle = MPI_GROUP_EMPTY;

    abi_mpi_info_env.handle = MPI_INFO_ENV;

    abi_mpi_message_no_proc.handle = MPI_MESSAGE_NO_PROC;

    abi_mpi_max.handle = MPI_MAX;
    abi_mpi_min.handle = MPI_MIN;
    abi_mpi_sum.handle = MPI_SUM;
    abi_mpi_prod.handle = MPI_PROD;
    abi_mpi_land.handle = MPI_LAND;
    abi_mpi_band.handle = MPI_BAND;
    abi_mpi_lor.handle = MPI_LOR;
    abi_mpi_bor.handle = MPI_BOR;
    abi_mpi_lxor.handle = MPI_LXOR;
    abi_mpi_bxor.handle = MPI_BXOR;
    abi_mpi_maxloc.handle = MPI_MAXLOC;
    abi_mpi_minloc.handle = MPI_MINLOC;
    abi_mpi_replace.handle = MPI_REPLACE;
    abi_mpi_no_op.handle = MPI_NO_OP;
}
