F77INCLUDES = -I.
smvar_do_sharedlibs = 0
LDADD = ../util/mtestf.o 
DEPADD = @MPILIBLOC@ ../util/mtestf.o

F77HEADERS = attraints.h

baseattrf_SOURCES    = baseattrf.f
baseattr2f_SOURCES    = baseattr2f.f
commattrf_SOURCES    = commattrf.f
commattr2f_SOURCES   = commattr2f.f
commattr3f_SOURCES   = commattr3f.f
typeattrf_SOURCES    = typeattrf.f
typeattr2f_SOURCES   = typeattr2f.f
typeattr3f_SOURCES   = typeattr3f.f

testing:
	../../runtests -srcdir=$(srcdir) -tests=testlist \
			-mpiexec=$(bindir)/mpiexec \
		   	-xmlfile=summary.xml

../util/mtestf.o: 
	(cd ../util && $(MAKE) mtestf.o)
