INCLUDES = -I../include -I${srcdir}/../include
LDADD = ../util/mtest.o 
DEPADD = @MPILIBLOC@ ../util/mtest.o
smvar_do_sharedlibs = 0

cartmap1_SOURCES = cartmap1.c
cartzero_SOURCES = cartzero.c
cartshift1_SOURCES = cartshift1.c
cartsuball_SOURCES = cartsuball.c
cartcreates_SOURCES = cartcreates.c
dims1_SOURCES = dims1.c
dims2_SOURCES = dims2.c
graphmap1_SOURCES = graphmap1.c
topotest_SOURCES = topotest.c
topodup_SOURCES = topodup.c
graphcr_SOURCES = graphcr.c
graphcr2_SOURCES = graphcr2.c
distgraph1_SOURCES = distgraph1.c
dgraph_unwgt_SOURCES = dgraph_unwgt.c

../util/mtest.o: 
	(cd ../util && make mtest.o)

testing:
	../runtests -srcdir=$(srcdir) -tests=testlist \
			-mpiexec=@MPIEXEC@ \
		   	-xmlfile=summary.xml
