lib${MPILIBNAME}_a_SOURCES = via_init.c via_get_business_card.c via_make_progress.c \
 via_can_connect.c via_post_connect.c via_post_read.c via_post_write.c
INCLUDES = -I../../include -I${top_srcdir}/include -I../../../../include -I${master_top_srcdir}/src/include
