SUBDIRS = channels src .

distclean-local:
	-rm -f include/mpidi_ch3_conf.h

maintainer-clean-local:
	-rm -f include/mpidi_ch3_conf.h.in

#
# echomaxprocname gives the maximum lenght of a processor name, as used
# by MPI_GET_PROCESSOR_NAME.  This is initialized in mpid_init
echomaxprocname:
	@echo 128
