INCLUDES = -I../include -I${srcdir}/../include
LDADD = ../util/mtest.o
DEPADD = @MPILIBLOC@ ../util/mtest.o
smvar_do_sharedlibs = 0

transp-datatype_SOURCES = transp-datatype.c
non_zero_root_SOURCES = non_zero_root.c
sendrecvl_SOURCES       = sendrecvl.c
twovec_SOURCES          = twovec.c
dtpack_SOURCES          = dtpack.c
allredtrace_SOURCES     = allredtrace.c
commcreatep_SOURCES     = commcreatep.c
timer_SOURCES		= timer.c
manyrma_SOURCES         = manyrma.c

../util/mtest.o:
	(cd ../util && $(MAKE) mtest.o)

# A special testing target to simplify running just the performance tests
testing:
	../runtests -srcdir=$(srcdir) -tests=testlist \
		   -mpiexec=@MPIEXEC@ \
		   -xmlfile=summary.xml

clean-local:
	-rm -f summary.xml
