DEPADD = @MPILIBLOC@ ../util/mtestf.o
smvar_do_sharedlibs = 0

baseenvf_SOURCES = baseenvf.f
baseenvf_LDADD = ../util/mtestf.o 
# Checksizes is created by configure, and is a C program that tests that 
# configure has correctly computed the sizes of MPI_Aint and MPI_Offset
# for Fortran.  This is not run by default but can be used to check
# that configure found the correct values.
checksizes_SOURCES = checksizes.c
checksizes_LDADD = 

testing:
	../../runtests -srcdir=$(srcdir) -tests=testlist \
			-mpiexec=$(bindir)/mpiexec \
		   	-xmlfile=summary.xml

../util/mtestf.o: 
	(cd ../util && $(MAKE) mtestf.o)
