smvar_do_sharedlibs = 0
INCLUDES = -I../../include -I${srcdir}/../../include
LDADD = ../util/mtest.o 
DEPADD = @MPILIBLOC@ ../util/mtest.o

winnamex_SOURCES = winnamex.cxx
getgroupx_SOURCES = getgroupx.cxx
winfencex_SOURCES = winfencex.cxx
winscale1x_SOURCES = winscale1x.cxx
winscale2x_SOURCES = winscale2x.cxx
wincallx_SOURCES = wincallx.cxx
fkeyvalwinx_SOURCES = fkeyvalwinx.cxx 

../util/mtest.o:
	cd ../util && $(MAKE) mtest.o

testing:
	../../runtests -srcdir=$(srcdir) -tests=testlist \
			-mpiexec=@MPIEXEC@ \
		   	-xmlfile=summary.xml
clean-local:
	-rm -f summary.xml
