INCLUDES = -I. -I../../include -I${master_top_srcdir}/src/ch3/channels/nemesis/nemesis/include -I${master_top_srcdir}/src/include \
           -I${top_builddir}/src/include
lib${MPILIBNAME}_a_SOURCES = \
  gm_module_finalize.c  gm_module_init.c  gm_module_poll.c      gm_module_send.c \
  gm_module_getput.c    gm_module_lmt.c   gm_module_register.c  gm_module_test.c
