# -*- Mode: Makefile; -*-
#
# (C) 2008 by Argonne National Laboratory.
#     See COPYRIGHT in top-level directory.
#

SUBDIRS_all_utils = args dbg env launch signals sock string timer plpa .
SUBDIRS = args dbg env launch signals sock string timer @all_utils@