smvar_do_sharedlibs = 0
INCLUDES = -I../../include -I${srcdir}/../../include
LDADD = ../util/mtest.o 
DEPADD = @MPILIBLOC@ ../util/mtest.o

bsend1cxx_SOURCES  = bsend1cxx.cxx
sendrecvx_SOURCES  = sendrecvx.cxx

../util/mtest.o:
	cd ../util && $(MAKE) mtest.o
