#! /usr/bin/env bash
##
## Copyright (C) by Argonne National Laboratory
##     See COPYRIGHT in top-level directory
##

# This script is used for CI testing, to use --
#    git rebase --verbose --exec maint/hooks/spellchecker [base-commit]

# Redirect output to stderr.
exec 1>&2

MIRROR=/tmp/${USER}/mpich-tmp-mirror
TMP_FILENAME=/tmp/${USER}/mpich-tmp-file

# Checkout a copy of the current index into MIRROR
git checkout-index --prefix=$MIRROR/ -af

# Remove files from MIRROR which are no longer present in the index
git diff-index --cached --name-only --diff-filter=D -z HEAD | \
    (cd $MIRROR && xargs -0 rm -f --)

# This will check the previous commit again when not amending a commit, but that
# should be ok if the patches are correct.
filestring=`git diff --cached --name-only --diff-filter=ACM HEAD~1`

# Everything else happens in the temporary build tree
pushd $MIRROR > /dev/null

ret=0

# This won't work if we ever have a file with a space in the name
for file in $filestring
do
    if [[ !($file == *.tex) ]] ; then
        cp ${file} ${TMP_FILENAME}
        bash maint/spellcheck.sh ${file}
        git --no-pager diff ${file} ${TMP_FILENAME}
        if [ $? != 0 ] ; then
            ret=1
        fi
    fi
done

rm -rf ${MIRROR} ${TMP_FILENAME}

if [ $ret != 0 ] ; then
    RED='\033[0;31m'
    NC='\033[0m' # No Color
    echo -e "${RED}== SPELLCHECKER SCRIPT FAILED ==${NC}"
    exit $ret
fi

popd > /dev/null
