#ifndef OFI_COLL_SELECT_INIT_H_INCLUDED
#define OFI_COLL_SELECT_INIT_H_INCLUDED

#undef FUNCNAME
#define FUNCNAME MPIDI_OFI_mpi_comm_collective_selection_init
#undef FCNAME
#define FCNAME MPL_QUOTE(FUNCNAME)
MPL_STATIC_INLINE_PREFIX int MPIDI_OFI_mpi_comm_collective_selection_init(MPIR_Comm * comm)
{
    int mpi_errno = MPI_SUCCESS;

    MPIR_FUNC_VERBOSE_STATE_DECL(MPID_STATE_MPIDI_OFI_COMM_COLLECTIVE_SELECTION_INIT);
    MPIR_FUNC_VERBOSE_ENTER(MPID_STATE_MPIDI_COMM_OFI_COLLECTIVE_SELECTION_INIT);

    MPIR_FUNC_VERBOSE_EXIT(MPID_STATE_MPIDI_COMM_OFI_COLLECTIVE_SELECTION_INIT);
    return mpi_errno;
}

#undef FUNCNAME
#define FUNCNAME MPIDI_OFI_mpi_comm_collective_selection_init
#undef FCNAME
#define FCNAME MPL_QUOTE(FUNCNAME)
MPL_STATIC_INLINE_PREFIX int MPIDI_OFI_mpi_comm_collective_selection_finalize(MPIR_Comm * comm)
{
    int mpi_errno = MPI_SUCCESS;

    MPIR_FUNC_VERBOSE_STATE_DECL(MPID_STATE_MPIDI_OFI_COMM_COLLECTIVE_SELECTION_FINALIZE);
    MPIR_FUNC_VERBOSE_ENTER(MPID_STATE_MPIDI_COMM_OFI_COLLECTIVE_SELECTION_FINALIZE);

    MPIR_FUNC_VERBOSE_EXIT(MPID_STATE_MPIDI_COMM_OFI_COLLECTIVE_SELECTION_FINALIZE);
    return mpi_errno;
}

#endif /* OFI_COLL_SELECT_INIT_H_INCLUDED */
