install_INCLUDE = ${srcdir}/include/mpix.h ${srcdir}/include/mpido_properties.h
SUBDIRS = src .

distclean-local:
	-rm -f include/mpidi_bg_conf.h

maintainerclean-local:
	-rm -f include/mpidi_bg_conf.h.in

echomaxprocname:
	@echo 131070
