lib${MPILIBNAME}_a_SOURCES = mpid_finalize.c mpid_init.c mpid_abort.c \
 mpid_get_processor_name.c
INCLUDES = -I../../include -I${top_srcdir}/include -I../../../../include -I${master_top_srcdir}/src/include
