/*
 * Copyright (C) by Argonne National Laboratory
 *     See COPYRIGHT in top-level directory
 */

#ifndef MPIDU_SHM_STATES_H_INCLUDED
#define MPIDU_SHM_STATES_H_INCLUDED

#define MPID_STATE_LIST_MPIDU_SHM \
MPID_STATE_MPIDU_SHM_BARRIER, \
MPID_STATE_MPIDU_SHM_BARRIER_INIT, \
MPID_STATE_MPIDU_SHM_SEG_ALLOC, \
MPID_STATE_MPIDU_SHM_SEG_FREE, \
MPID_STATE_MPIDU_SHM_SEG_IS_SYMM, \
MPID_STATE_MPIDU_SHM_CHECK_ALLOC, \
MPID_STATE_MPIDU_INIT_SHM_SEG_INIT, \
MPID_STATE_MPIDU_INIT_SHM_SEG_FINALIZE, \
MPID_STATE_MPIDU_INIT_SHM_SEG_BARRIER, \
MPID_STATE_MPIDU_INIT_SHM_SEG_PUT, \
MPID_STATE_MPIDU_INIT_SHM_SEG_GET,

#endif /* MPIDU_SHM_STATES_H_INCLUDED */
