name: ci

on:  # yamllint disable-line rule:truthy
  push:
    branches:
      - "main"
      - "[0-9]+.[0-9]+.x"
  pull_request:
    branches:
      - "main"
      - "[0-9]+.[0-9]+.x"
  workflow_dispatch:
    inputs:
      Linux:
        description: 'Linux'
        required: true
        type: boolean
        default: true
      macOS:
        description: 'macOS'
        required: true
        type: boolean
        default: true

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

permissions:
  contents: read

jobs:

  Linux:
    if: |-
      ${{ case(
        github.event_name == 'workflow_call' ||
        github.event_name == 'workflow_dispatch',
        inputs.Linux,
        true
      ) }}
    strategy:
      fail-fast: false
      matrix:
        arch:
          - aarch64
          - x86_64
        device:
          - ch4:ucx
          - ch4:ofi
          - ch3:nemesis
          - ch3:sock
        pm:
          - hydra
          - gforker
    uses: ./.github/workflows/ci-workflow.yml
    with:
      runs-on: Linux-${{ matrix.arch }}
      device:  ${{ matrix.device }}
      pm:      ${{ matrix.pm     }}

  macOS:
    if: |-
      ${{ case(
        github.event_name == 'workflow_call' ||
        github.event_name == 'workflow_dispatch',
        inputs.macOS,
        true
      ) }}
    strategy:
      fail-fast: false
      matrix:
        arch:
          - arm64
          - x86_64
        device:
          - ch4:ofi
          - ch3:nemesis
          - ch3:sock
        pm:
          - hydra
          - gforker
    uses: ./.github/workflows/ci-workflow.yml
    with:
      runs-on: macOS-${{ matrix.arch }}
      device:  ${{ matrix.device }}
      pm:      ${{ matrix.pm     }}
